Make decorators skip tests before setup
openpbs/openpbs pull request #1933
Opened 2020-07-27 11:29 UTC by minghui-liu

fix issues with multiple decorators

#### Describe Bug or Feature

#### Describe Your Change

#### Link to Design Doc

#### Attach Test and Valgrind Logs/Output

2020-08-18 16:34 UTC, hirenvadalia commented
@minghui-liu Agree with @bayucan, Nice work! I like idea of how we are skipping test now, this will speed of PTL runs by not running setUp when we want to skip test... however we still needs optimize/fix new methods (aka cls.skip_* methods), I will add those comments soon...
One que @minghui-liu: Can you please try using this approach by putting skip decorators on class instead test and see whether all tests in that class are getting skipped or not? (BTW I am totally fine if we say we don't support skip decorators on class level and we have to put on each test)

2020-08-19 07:02 UTC, minghui-liu commented
Thank you @hirenvadalia for your comment. Unfortunately the decorators do not work on the class level. They have to be put on each test case.

2020-08-19 09:14 UTC, minghui-liu commented
I have uploaded the test results of skipping a whole test suite, they were appended at the end.

2020-08-19 09:27 UTC, hirenvadalia requested changes

2020-08-19 09:27 UTC, hirenvadalia commented on test/fw/ptl/utils/pbs_testsuite.py
> +        cls.test_list = [attr for attr in dir(cls)
I think we should make this dict of (name, obj) (aka (attr, getattr(cls, attr)) so in below func we don't have to call getattr again for each test

2020-08-19 09:27 UTC, hirenvadalia commented on test/fw/ptl/utils/pbs_testsuite.py
> +        if '__skip_on_cray__' in cls.__dict__ \
you can simple do `if cls.__dict__.get('__skip_on_cray__', False):`
(same for others)

2020-08-19 09:27 UTC, hirenvadalia commented on test/fw/ptl/utils/pbs_testsuite.py
> +            return
rather than return how out if/else? like
if check for class:
else:
   for each test

2020-08-19 09:27 UTC, hirenvadalia commented on test/fw/ptl/utils/pbs_testsuite.py
> +                msg = 'capability not supported on cgroup cpuset system: ' +\
please use += format instead +\

2020-08-20 06:37 UTC, hirenvadalia approved these changes
Thanks @minghui-liu for addressing comments, LGTM.
Please full regression once just to ensure we are not breaking anything...

2020-08-20 22:12 UTC, merged

2020-08-20 22:12 UTC, bayucan commented
Merge #1933 to master.