[WIP] Fix: pbs_python fails to initialize
openpbs/openpbs pull request #1980
Opened 2020-08-19 11:20 UTC by raviv1995

#### Describe Bug or Feature
pbs_python fails to initialize because of a missing '/'.

#### Describe Your Change
Added the missing '/'
Refactoring some MoM & MoM-hook env related funcs.

#### Attach Test and Valgrind Logs/Output

2020-08-24 09:52 UTC, npadole20 requested changes
Please attach test logs.

2020-08-24 09:52 UTC, npadole20 commented on src/resmom/mom_hook_func.c
> +			hook_env = dup_string_arr(pjob->ji_env);
What happens if dup_string_arr() fails? We should exit in that case.

2020-08-27 16:11 UTC, bayucan commented
@raviv1995 : I think @npadole20 has a question for you...

2020-08-28 03:55 UTC, npadole20 commented
@bayucan  @raviv1995  has made the change at https://github.com/openpbs/openpbs/pull/1980/files#diff-f000d05f102c29b1985e578963befa7aR1517
@raviv1995  the changes look good to me. please attach test logs.

2020-08-28 04:37 UTC, npadole20 approved these changes

2020-09-04 09:33 UTC, subhasisb commented on src/resmom/requests.c
> +		free_string_array(pjob->ji_env);
why freeing ji_env out of the blue?

2020-09-04 09:34 UTC, subhasisb commented on src/server/job_func.c
> +	if (pjob->ji_env != NULL)
had u initialized ji_env to nULL in job_alloc()?

2020-09-04 09:40 UTC, subhasisb requested changes

2020-09-04 09:40 UTC, subhasisb commented on src/server/job_func.c
> +	if (pjob->ji_env != NULL)
u dont need to check for NULL before calling free_string_array()

2020-09-04 09:40 UTC, subhasisb commented on src/resmom/mom_main.c
> +	env_array = bld_wenv_variables("UID", buf, env_array);
check if bld_wenv_variables() can be deprecated in lieu of the mainstream bld_env_variables() function. Basically, we should try to reuse bld_env_variables() and modify that if it needs enhancement

2020-09-18 08:43 UTC, subhasisb approved these changes

2020-09-18 08:44 UTC, merged

2020-09-18 08:48 UTC, raviv1995 commented
Thanks for the review @bayucan @npadole20 @subhasisb