Fix return code for local and remote stage-out
openpbs/openpbs pull request #2003
Opened 2020-08-27 06:27 UTC by SudeshnaMoulik

#### Describe Bug or Feature
In some platform pbs_stage_file reports wrong number of file copied out successfully.

07/30/2020 09:22:56;0004;PBS_stage_file;Fil;2001.win2012-vm1.ER;Unable to copy file C:/PROGRA~2/PBS/home/spool/2001.win2012-vm1.ER to win2012-vm1:C:/Users/sudemo/Desktop/STDIN.e2001
07/30/2020 09:22:56;0004;PBS_stage_file;Fil;2001.win2012-vm1.ER;rcp: C:\Users/sudemo/Desktop\STDIN.e2001: No such file or directory
07/30/2020 09:22:56;0100;PBS_stage_file;Job;2001.win2012-vm1;Staged 2/2 items out over 0:00:01

#### Describe Your Change
If stage-out fails, we are not setting the return code value in copy_file() and sys_copy().

#### Link to Design Doc

#### Attach Test and Valgrind Logs/Output

Description: Tests from given sources on platforms UBUNTU1804, SUSE15, UBUNTU1604, CENTOS8, RHEL8, WIN2K16, CENTOS7
Platforms: UBUNTU1804,SUSE15,UBUNTU1604,CENTOS8,RHEL8,WIN2K16,CENTOS7
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|3334|3443|3|0|1|2|3437|

Description: Rerun Only Failed Tests From #3334
Platforms: UBUNTU1804,SUSE15,UBUNTU1604,CENTOS8,RHEL8,WIN2K16,CENTOS7
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|3338|4|0|0|0|0|4|

2020-08-27 12:45 UTC, npadole20 commented
@SudeshnaMoulik I am not able to access the mom_log.txt file.

2020-08-27 14:47 UTC, Shrini-h requested changes

2020-08-27 14:47 UTC, Shrini-h commented on src/resmom/requests.c
> +	bool copy_failed = FALSE;
```suggestion
	int			tot_copies = 0;
	bool			copy_failed = FALSE;
```

2020-08-28 04:58 UTC, npadole20 approved these changes

2020-08-28 05:25 UTC, Shrini-h approved these changes
LGTM

2020-08-28 05:29 UTC, subhasisb approved these changes

2020-08-28 05:29 UTC, merged