Multi-sched test fails on slow machines
openpbs/openpbs pull request #2027
Opened 2020-09-12 02:57 UTC by arungrover

#### Describe Bug or Feature
Multi-sched test submits a reservation and then waits for it to be confirmed. This test then offlines the vnode where the reservation was confirmed and then checks that the reservation gets reconfirmed on another vnode.
This test fails on slow machines because the reservation is submitted to start 20 seconds in the future and by the time the test creates all schedulers, offlines the node, and checks the reservation's node and status, the reservation moves into running state.

#### Describe Your Change
This change now submits a reservation that will start 40 seconds in the future. This gives the test enough time on slower machines to offline a vnode, and create schedulers. This change should not delay the test on faster machines because the test does not wait for the reservation to start.

#### Link to Design Doc
NA

#### Attach Test and Valgrind Logs/Output
[test_multisched.txt](https://github.com/openpbs/openpbs/files/5212091/test_multisched.txt)

2020-09-14 18:51 UTC, bhroam requested changes

2020-09-14 18:51 UTC, bhroam commented on test/tests/functional/pbs_multi_sched.py
> -        self.degraded_resv_reconfirm(start=now + 20, end=now + 200,
Since the test does not wait for the reservation to start, why not use now + 600 and now + 800 just to be safe?

2020-09-14 23:53 UTC, bhroam approved these changes
LGTM

2020-09-15 18:07 UTC, vstumpf approved these changes
LGTM

2020-09-15 18:08 UTC, merged