clean up mom code around fork()
openpbs/openpbs pull request #2031
Opened 2020-09-16 17:33 UTC by Shrini-h

#### Describe Bug or Feature

Some code around fork calls in mom needed simplification

#### Describe Your Change

made the code around fork in mom platform independent by utilizing ENOSYS errno set by fork where fork is not available

#### Attach Test and Valgrind Logs/Output

Pending

2020-09-28 10:14 UTC, SudeshnaMoulik requested changes

2020-09-29 09:15 UTC, Shrini-h commented on src/cmds/pbs_attach.c
> +extern char *get_ecname(int);
Fixed in https://github.com/openpbs/openpbs/pull/2031/commits/78f5d5a3803579fad4f2eba71d08cbd737d6073d

2020-09-29 09:15 UTC, Shrini-h commented on src/cmds/pbs_attach_sup.c
> + * @param[in] use_cmd : if TRUE, launch the process using a new command shell.
fixed in https://github.com/openpbs/openpbs/pull/2031/commits/78f5d5a3803579fad4f2eba71d08cbd737d6073d

2020-09-30 08:10 UTC, SudeshnaMoulik approved these changes

2020-09-30 17:51 UTC, bayucan approved these changes
Looks good.

2020-10-05 06:12 UTC, SudeshnaMoulik approved these changes

2020-10-05 19:57 UTC, merged