Move PTL create_vnodes method from class Server to Mom
openpbs/openpbs pull request #2033
Opened 2020-09-17 09:23 UTC by visheshh

#### Describe Bug or Feature
Move PTL create_vnodes method from class Server to Mom

#### Describe Your Change
1.Moved PTL create_vnodes method from class Server to Mom
2. Removed the mom object and the vnode_prefix name sent to create_vnodes function and added back an optional vnode_prefix which can be given under necessary conditions.
3.Make mom hostname as the default vnode_prefix and removed the vnode_prefix from tests if not absolutely necessary.
4. Modified TestOfflineVnode test suite to verify vnodes from both the moms.

#### Link to Design Doc

#### Attach Test and Valgrind Logs/Output

2020-09-17 21:08 UTC, bhroam requested changes

2020-09-17 21:08 UTC, bhroam commented on test/tests/functional/pbs_test_tpp.py
> +                "[0]:ncpus=1+vnode=" + vn + "[1]:ncpus=1"
Consider using string formatting.  If you do that, you might be able to put the string on the first line and the (vn, vn) on the second.

2020-09-17 21:08 UTC, bhroam commented on test/tests/functional/pbs_test_tpp.py
>                            self.server.status(NODE)[2]['id']]
Only call status() once, and and call ret[0]['id'] and ret[1]['id]], or use list comprehension and say [ret[i]['id'] for i in range(2)] (here and above)

2020-09-17 22:50 UTC, agrawalravi90 submitted a review, later dismissed
"Move PTL create_vnodes method from class Server to Mom"

Can you please explain the motivation to do this?

2020-09-18 04:36 UTC, visheshh commented
> 
> 
> "Move PTL create_vnodes method from class Server to Mom"
> 
> Can you please explain the motivation to do this?

Hi @agrawalravi90 ,
Motivation to do this was to make vnode prefixes same across all platforms such as cpuset moms.
We are removing skipcpuset decorator and trying to return available vnodes in the system which have mom name as prefix and tests use vn or vnode as prefix, so we removed them and in the process moved create_vnodes function which has nothing do with server object and instead of calling from server object and passing mom object as argument we moved it under class mom.

2020-09-18 04:37 UTC, visheshh commented
Thanks @bhroam for taking your time and doing a quick review for all of these tests.

2020-09-21 13:40 UTC, visheshh commented
Hi @bhroam, I have addressed all comments. Please review.

2020-09-21 19:08 UTC, bhroam requested changes

2020-09-23 02:26 UTC, visheshh commented
@bhroam Please review

2020-09-23 21:54 UTC, bhroam approved these changes
LGTM

2020-10-03 01:29 UTC, arungrover approved these changes
LGTM

2020-10-03 01:30 UTC, merged