[WIP] Refactoring some unsupported code
openpbs/openpbs pull request #2042
Opened 2020-09-24 05:39 UTC by raviv1995

#### Describe Bug or Feature

Some unsupported platform code has been removed

#### Attach Test and Valgrind Logs/Output

2020-10-06 15:50 UTC, npadole20 requested changes

2020-10-07 09:59 UTC, Shrini-h requested changes

2020-10-07 09:59 UTC, Shrini-h commented on src/cmds/qsub.c
> +	close(sock);
You wont need this line. see https://github.com/openpbs/openpbs/pull/1917/files#diff-6248e35fa28821a275554b0df12547b1R1413-R1418

2020-10-07 09:59 UTC, Shrini-h commented on src/include/portability.h
> +#define critical_section()  NULL
I think the `NULL` is not needed and may be left empty

2020-10-07 13:23 UTC, npadole20 requested changes

2020-10-07 19:17 UTC, raviv1995 commented on src/cmds/qsub.c
> +block(void)
This is used in case the block option is provided. Check line 3322

2020-10-07 20:01 UTC, Shrini-h approved these changes

2020-10-07 22:34 UTC, bayucan commented
Please rebase this to the latest OSS master and see if there's any conflict.

2020-10-08 13:01 UTC, Shrini-h commented on src/cmds/qsub.c
> +
May be this is not necessary. please see if this can be removed

2020-10-09 18:05 UTC, bayucan reviewed
Looks good. 
@npadole20 : need your sign off on this before merge.

2020-10-14 04:13 UTC, npadole20 approved these changes
Changes look good to me.

2020-10-14 19:23 UTC, bayucan approved these changes
Looks good.

2020-10-14 19:25 UTC, merged

2020-10-14 19:25 UTC, bayucan commented
Merged #2042 into master.