Fixing a bug with --disable-security-check flag
openpbs/openpbs pull request #2080
Opened 2020-10-19 22:14 UTC by agrawalravi90

#### Describe Bug or Feature

We were disabling security always, this fixes it

#### Describe Your Change

#### Link to Design Doc

#### Attach Test and Valgrind Logs/Output

2020-10-19 22:23 UTC, vstumpf requested changes

2020-10-19 22:23 UTC, vstumpf commented on m4/security_check.m4
> +    AC_DEFINE([NO_SECURITY_CHECK], [1], [Define as 1 to disable security check, 1 to enable])
I don't understand this comment, 1 to disable, 1 to enable.
Should this be something like
`AC_DEFINE([NO_SECURITY_CHECK], [], [Defined when skipping security checks])`

2020-10-20 18:25 UTC, arungrover approved these changes
LGTM

2020-10-20 18:55 UTC, vstumpf approved these changes
LGTM

2020-10-20 19:04 UTC, vstumpf commented
Here's some test logs:
Default:
```
[vstumpf@shecil pbspro]$ ./configure | grep security
checking whether to disable security check... no
[vstumpf@shecil pbspro]$ cat src/include/pbs_config.h | grep SECURITY
/* #undef NO_SECURITY_CHECK */
/* #undef PBS_SECURITY */
```

enable security checks
```
[vstumpf@shecil pbspro]$ ./configure --enable-security | grep security
checking whether to disable security check... no
[vstumpf@shecil pbspro]$ cat src/include/pbs_config.h | grep SECURITY
/* #undef NO_SECURITY_CHECK */
/* #undef PBS_SECURITY */
[vstumpf@shecil pbspro]$ 
```

disable security checks
```
[vstumpf@shecil pbspro]$ ./configure --disable-security | grep security
checking whether to disable security check... yes
[vstumpf@shecil pbspro]$ cat src/include/pbs_config.h | grep SECURITY
#define NO_SECURITY_CHECK /**/
/* #undef PBS_SECURITY */
```

2020-10-20 19:04 UTC, merged

2020-10-20 20:00 UTC, agrawalravi90 commented
Thanks for the merge @vstumpf !