systemd missing daemons only start
openpbs/openpbs pull request #2104
Opened 2020-11-03 18:18 UTC by Jitendra-Rajak

#### Describe Bug or Feature
If PBS is started using systemd and if some how any daemon get killed, systemctl status still shows pbs service running without the daemon in process list that got killed. We were not able to start that missing daemon until we restart the service all together.

#### Describe Your Change
Added a directive in the pbs.service unit file that will be used to reload pbs service by doing the reload only the missing daemon/ daemons will be started again and will be seen in the process list when we do systemctl status pbs.

#### Link to Design Doc

#### Attach Test and Valgrind Logs/Output

[res_systemd.txt](https://github.com/openpbs/openpbs/files/5483196/res_systemd.txt)

|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|4637|3845|5|0|0|0|3840|

2020-11-10 14:22 UTC, Jitendra-Rajak commented
travis passed @prakashcv13 , It was a pep8 error.

2021-02-02 09:56 UTC, prakashcv13 requested changes

2021-02-02 09:56 UTC, prakashcv13 commented on src/cmds/scripts/pbs_wrap.in
> +cgpath=/sys/fs/cgroup/systemd/system.slice/pbs.service
why use a hard-coded path?
is there a possibility that cgroupfs is mounted on a different location?

2021-02-05 05:01 UTC, subhasisb commented
stale PR - closing for now. Please reopen when work progresses

2021-02-05 05:01 UTC, closed without merging