Multinode test fixes
openpbs/openpbs pull request #2115
Opened 2020-11-10 15:49 UTC by npadole20

#### Describe Bug or Feature

Fixes for some multi node tests

#### Describe Your Change

* Modified __are_requirements_matching() to get system information based on platform. 
* Increased job sleep time in test_rerun_on_epilogue_hook because sometimes the job finishes before job substate is sent to server
* Changed restart() to start() in test_momhook_to_serverhook_with_restart and test_momhook_to_momhook_with_restart as we have already stopped mom

#### Link to Design Doc

NA

#### Attach Test and Valgrind Logs/Output

Description: Tests from given sources on platforms UBUNTU1804, SUSE15, UBUNTU1604, CENTOS8, RHEL8, CENTOS7, RHEL7, SLES12, SLES15, WIN2K16
Platforms: UBUNTU1804,SUSE15,UBUNTU1604,CENTOS8,RHEL8,CENTOS7,RHEL7,SLES12,SLES15,WIN2K16
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|4765|2982|3|0|0|0|2979|

The failed tests are known failures.

2020-11-11 00:08 UTC, bhroam requested changes

2020-11-11 00:08 UTC, bhroam commented on test/fw/ptl/utils/plugins/ptl_test_runner.py
> +            for mc in mlist:
Since this is the only use of mlist, why not put this block inside the above if

2020-11-11 00:08 UTC, bhroam commented on test/tests/functional/pbs_mom_hook_sync.py
> +                                   sudo=True)
As above, I don't see the purpose of self.mom.cat() unless you remove the hostname param.  I still don't really see the purpose then, but it at least makes a little more sense.  Doing self.mom.cat(some_nonmom_hostname, ...) makes no sense to me.

2020-11-12 20:41 UTC, bhroam commented on test/fw/ptl/utils/plugins/ptl_test_runner.py
> +            if mlist:
No need for mlist any more.  Just put getattr(_test, name).values() in the for below

2020-11-19 20:35 UTC, bhroam approved these changes
LGTM

2020-11-20 04:55 UTC, sakshamgarg approved these changes
Changes look good to me.

2020-11-20 18:22 UTC, merged