fix eatcpu script failure if mom is on remote host
openpbs/openpbs pull request #2121
Opened 2020-11-12 11:01 UTC by dinesh1306

#### Describe Bug or Feature
fix eatcpu script failure if mom is on remote host. 
Current code create temp_eatcpu_script on mom, but when we have remote mom PTL try to copy temp_eatcpu_script file from current host to remote mom user home directory, but we created temp_eatcpu_script on mom only due to PTL didn't get expected file for copy and failed.

#### Describe Your Change
As we are creating temp_eatcpu_script on mom, no need of copy created temp_eatcpu_script to remote mom users home directory. removed code for file copy. 

#### Link to Design Doc

#### Attach Test and Valgrind Logs/Output
**Before fix:**
[res_before_fix.txt](https://github.com/openpbs/openpbs/files/5530046/res_before_fix.txt)

**After Fix:**
MoM on same host:
Description: PBSMoM on same host
Platforms: CENTOS7,CENTOS8,SUSE15,UBUNTU1804
Profile: Custom
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|4824|4|0|0|0|0|4|

[res_test_finished_jobs_mom_on_same_host.txt](https://github.com/openpbs/openpbs/files/5530066/res_test_finished_jobs_mom_on_same_host.txt)

MoM on remote host:
Description: Tests from given sources on platforms CENTOS7, CENTOS8, SUSE15, UBUNTU1804
Platforms: CENTOS7,CENTOS8,SUSE15,UBUNTU1804
Profile: Custom
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|4823|4|0|0|0|0|4|

[res_test_finished_jobs_mom_on_different_host.txt](https://github.com/openpbs/openpbs/files/5530069/res_test_finished_jobs_mom_on_different_host.txt)

2020-11-13 06:00 UTC, vishwaks requested changes

2020-11-13 06:00 UTC, vishwaks commented on test/tests/pbs_smoketest.py
> +        a = {'Resource_List.ncpus': 2, ATTR_k: 'oe'}
Just wondering, why do we need -koe for this change ?

2020-11-13 09:46 UTC, vishwaks approved these changes

2020-11-13 17:21 UTC, dinesh1306 commented
res after change.


MoM on same host.
Description: MoM on same host
Platforms: CENTOS8,SUSE15,UBUNTU1804
Profile: Custom
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|4852|3|0|0|0|0|3|

MoM on remote host.
Description: MoM on remote Host
Platforms: CENTOS8,SUSE15,UBUNTU1804
Profile: Custom
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|4845|3|0|0|0|0|3|

2020-11-24 01:13 UTC, birbalsain approved these changes
LGTM

2020-11-24 08:27 UTC, hirenvadalia approved these changes

2020-11-24 08:27 UTC, merged