Fix usigned integer underflow in primetime
openpbs/openpbs pull request #2124
Opened 2020-11-13 22:31 UTC by vstumpf

#### Describe Bug or Feature
The scheduler would think that primetime wouldn't start until sometime in the year 2156.

#### Describe Your Change
Since primetime was stored as an unsigned integer, subtracting a greater number from it would cause an integer underflow, causing the difference to be some 4 billion seconds.

#### Link to Design Doc

#### Attach Test and Valgrind Logs/Output
It's not feasible to create a test for this, since it only happens if the primetime's start-time's minutes value is behind the current time.

```
# good
[root@shecil sched_priv]# date
Fri Nov 13 14:46:59 PST 2020
[root@shecil sched_priv]# cat holidays
YEAR    2020
weekday 1530    1535
[root@shecil sched_priv]# qmgr -c "s s scheduling=t"
[root@shecil sched_priv]# tail -n 10 /var/spool/pbs/sched_logs/20201113 | grep primetime
11/13/2020 14:47:10.719499;0100;pbs_sched;Svr;;It is non-primetime.  It will end in 2570 seconds at 11/13/2020 15:30:00
```

```
# bad
[root@shecil sched_priv]# date
Fri Nov 13 14:50:56 PST 2020
[root@shecil sched_priv]# cat holidays
YEAR    2020
weekday 1530    1535
[root@shecil sched_priv]# qmgr -c "s s scheduling=t"
[root@shecil sched_priv]# tail -n 10 /var/spool/pbs/sched_logs/20201113 | grep primetime
11/13/2020 14:51:32.360895;0100;pbs_sched;Svr;;It is non-primetime.  It will end in 4294969604 seconds at 12/20/2156 21:58:16
```

2020-11-14 01:41 UTC, bhroam requested changes
Why cast the unsigned away when you can just make it a normal int?

2020-11-14 04:00 UTC, vstumpf commented
It was always unsigned to begin with, I guess I can make it a normal int, It will require some more changes to remove all the unsigned int casts.

2020-11-16 21:48 UTC, bhroam approved these changes
LGTM

2020-11-17 18:00 UTC, vstumpf commented
Please re-review (review? re<sup>2<sup>view?)

2020-11-17 20:58 UTC, bhroam approved these changes

2020-11-17 21:21 UTC, arungrover approved these changes
LGTM

2020-11-17 21:22 UTC, merged