Fix few tests from 'TestResourceUsageLog' when mom is on remote host
openpbs/openpbs pull request #2126
Opened 2020-11-17 08:38 UTC by Klovely

#### Describe Bug or Feature
All these three test cases
./TestResourceUsageLog/test_acclog_force_requeue
./TestResourceUsageLog/test_acclog_for_job_states
./TestResourceUsageLog/test_acclog_preempt_order
failed  with PTL expect error
ptl.lib.ptl_error.PtlExpectError: rc=1, rv=False, msg=expected on server xyz-r8:  no data for job_state = R && substate = 42 job 8.xyz-r8 attempt: 180

create_eatcpu_job() is not working  when mom is onn remote host , due to this job is getting submitted in test is just getting submitted and terminated with resource_used_walltime=0 
resources_used.walltime = 00:00:00
sub state = 41
so test failed to get job_state=R and sub state=42 and failed with expect error.

 
#### Describe Your Change
Pass self.mom.shortname in create_eatcpu_job() to work test on setup where mom is on remote host 

Note : -
[#2121](https://github.com/openpbs/openpbs/pull/2121) is already raised to handle eatcpu script to work  on remote host as well.
taken 'ptl_resourceresv.py' changes in my branch , and done changes for TestResourceUsageLog
As part of this ticket  I have taken 'ptl_resourceresv.py' changes in my branch , and done changes in test of TestResourceUsageLog to work on remote host .

#### Attach Test and Valgrind Logs/Output
Before fix 
[before_fix_TestResourceUsageLog.txt](https://github.com/openpbs/openpbs/files/5552193/before_fix_TestResourceUsageLog.txt)

After fix
[after_fix_TestResourceUsageLog.txt](https://github.com/openpbs/openpbs/files/5552195/after_fix_TestResourceUsageLog.txt)
[after_fix_TestResourceUsageLog_non_mom_on_server.txt](https://github.com/openpbs/openpbs/files/5552197/after_fix_TestResourceUsageLog_non_mom_on_server.txt)

2020-11-24 01:56 UTC, birbalsain requested changes
Please also change create_eatcpu_job() in tests "test_acclog_mom_down", "test_acclog_job_multiple_qrerun" and "test_acclog_services_restart".

2020-11-25 08:32 UTC, Klovely commented
latest logs
[TestResourceUsageLog_no_mom_on_server.txt](https://github.com/openpbs/openpbs/files/5595346/TestResourceUsageLog_no_mom_on_server.txt)

2020-11-26 06:43 UTC, birbalsain approved these changes
LGTM

2020-11-26 06:56 UTC, prakashcv13 approved these changes

2020-11-26 06:56 UTC, merged