Preemption fails when host or vnode is requested at chunk level
openpbs/openpbs pull request #2143
Opened 2020-12-03 02:03 UTC by arungrover

#### Describe Bug or Feature
PBS scheduler while trying to preempt a job tries to limit the number of preemption candidates by checking the reason why a high priority job could not run and then cull the preemptible jobs to only those jobs who can help in running the high priority job.
While doing so, it takes special care about non-consumable resource vnode and host. The issue while checking these resources was that it was assumed these two are job wide resources and thus they are requested for the whole job. But this assumption is incorrect, one can request a multinode job to have one chunk running on a specific vnode or host.
Scheduler was crashing because of this wrong assumption.

#### Describe Your Change
In this change, we try to retain the value of vnode/host because of which the job could not run in the error structure. We store it in arg2 of error structure. Then in cull_preemptible_jobs, instead of searching though all the chunks and finding out which chunk requested the resource that caused the job to not run, we now use the arg2 member of error structure that stores the name of the vnode/host because of which the job could not run.

#### Link to Design Doc
NA

#### Attach Test and Valgrind Logs/Output
[test_preemption_before.txt](https://github.com/openpbs/openpbs/files/5633185/test_preemption_before.txt)
[test_preemption.txt](https://github.com/openpbs/openpbs/files/5633188/test_preemption.txt)

2020-12-03 23:42 UTC, vstumpf commented on src/scheduler/check.cpp
> +						char *requested;
Can you make this a `const char *`? Eventually I'd like `res_to_str_r` return a `const char *`,

2020-12-07 21:00 UTC, bhroam approved these changes
LGTM

2020-12-08 21:11 UTC, vstumpf requested changes
LGTM

2020-12-08 21:11 UTC, vstumpf reviewed
LGTM

2020-12-08 21:12 UTC, vstumpf approved these changes
LGTM (third time's the charm)

2020-12-08 21:12 UTC, merged