Fix for pbs_tmrsh invoked from sister moms failure
openpbs/openpbs pull request #2147
Opened 2020-12-04 06:24 UTC by sujatapatnaik52

#### Describe Bug or Feature
pbs_tmrsh invoked from sister moms fails with "cannot find PBS_NODEFILE".

#### Describe Your Change
1. PBS_NODEFILE environment variable to be set in sister mom. 
2. PBS_NODEFILE to be created in sister moms. 
3. The above change is enabled by default. For disabling it, a new boolean mom config parameter is introduced i.e. $secondary_pbs_nodefile

After making the above changes, the invocation was still failing with this error message - "start_process, no stream to MS". Explicitly initializing the mother superior's stream resolves this. 

#### Attach Test and Valgrind Logs/Output

[TestSecondaryPBSNodefile.txt](https://github.com/openpbs/openpbs/files/5640835/TestSecondaryPBSNodefile.txt)
[TestJobTask.txt](https://github.com/openpbs/openpbs/files/5640836/TestJobTask.txt)

2020-12-05 13:14 UTC, prakashcv13 requested changes

2020-12-05 13:14 UTC, prakashcv13 commented on test/tests/functional/pbs_job_task.py
> +            self.skipTest("test requires atleast three MoMs as input, " +
checking for exactly 3, so we can remove "atleast"

2020-12-05 13:14 UTC, prakashcv13 commented on test/tests/functional/pbs_secondary_pbs_nodefile.py
> +            self.skipTest("test requires atleast two MoMs as input, " +
here as well - we can remove "atleast"

2020-12-07 15:38 UTC, prakashcv13 approved these changes

2020-12-07 16:16 UTC, subhasisb requested changes

2020-12-07 16:16 UTC, subhasisb commented on src/resmom/catch_child.c
> +extern int secondary_pbs_nodefile;
I think the name is confusing - secondary_pbs_nodefile can be confused with what we doing in other hook

2020-12-07 16:16 UTC, subhasisb commented on src/resmom/catch_child.c
> +extern int secondary_pbs_nodefile;
also is this aligned? If so, please align the other variables as well

2020-12-07 16:16 UTC, subhasisb commented on src/resmom/catch_child.c
> +	if (pjob->ji_qs.ji_svrflags & JOB_SVFLG_HERE || secondary_pbs_nodefile) {
i would think that a better name might be something like "gen_nodefile_on_sister_mom"?

2020-12-07 16:16 UTC, subhasisb commented on src/resmom/mom_comm.c
> +extern int secondary_pbs_nodefile;
indent?

2020-12-08 04:02 UTC, sujatapatnaik52 commented
[TestGenNodefileOnSisterMom.txt](https://github.com/openpbs/openpbs/files/5656769/TestGenNodefileOnSisterMom.txt)
[TestJobTask.txt](https://github.com/openpbs/openpbs/files/5656770/TestJobTask.txt)

2020-12-08 04:03 UTC, sujatapatnaik52 commented
@subhasisb Please review the latest commits.

2020-12-08 04:05 UTC, subhasisb requested changes

2020-12-08 04:05 UTC, subhasisb commented on src/resmom/catch_child.c
> +extern char		*		path_hooks_workdir;
now there is a tab between * and path_hooks_workdir

2020-12-08 04:05 UTC, subhasisb commented on src/resmom/mom_main.c
> +static handler_ret_t	set_gen_nodefile_on_sister_mom(char *);
per our updated coding standards, variables and declarations need not be aligned - so you need to remove the alignment of all the blocks u touch

2020-12-08 04:05 UTC, subhasisb commented on src/resmom/mom_comm.c
> +extern int 		gen_nodefile_on_sister_mom;
per our updated coding standards, variables and declarations need not be aligned - so you need to remove the alignment of all the blocks u touch

2020-12-08 04:05 UTC, subhasisb commented on src/resmom/catch_child.c
> +extern int 		gen_nodefile_on_sister_mom;
per our updated coding standards, variables and declarations need not be aligned - so you need to remove the alignment of all the blocks u touch

2020-12-08 04:39 UTC, subhasisb approved these changes

2020-12-08 04:52 UTC, sujatapatnaik52 commented
One of the travis builds failed, force-pushing to restart it.

2020-12-08 08:40 UTC, merged