qsub should distribute jobs uniformly amongst server instances
openpbs/openpbs pull request #2192
Opened 2021-01-07 18:39 UTC by nithinj

#### Describe Bug or Feature
qsub daemon was distributing jobs randomly which could result in skewed submissions

#### Describe Your Change
Instead of random, pbs_submit will pick the next available instance from the list based on the last used instance.

#### Attach Test and Valgrind Logs/Output
```
[root@centos8 pbspro]# for i in {1..6}; do qsub -- /bin/sleep 100; done
29.centos8_2
60.centos8
30.centos8_2
61.centos8
31.centos8_2
62.centos8
````

2021-01-07 18:39 UTC, nithinj commented
Requesting reviews from @suresh-thelkar

2021-01-07 20:37 UTC, agrawalravi90 requested changes
I'm not sure that this is any better than random, if not worse. This will only work if all jobs are being submitted from the same qsub daemon process. In practice, you'll have multiple users submitting jobs from their own terminals. In the worst case, if all users submit jobs in lock step, you'll get all jobs submitted to only one server at a time (all N users will choose server 1 first and submit N jobs to server 1, then N jobs to server 2 and so on).

2021-01-07 20:47 UTC, arungrover commented
Any route you choose, please also take care of job dependency. Dependent jobs should ideally go to the same server.

2021-01-07 20:51 UTC, agrawalravi90 commented
> Any route you choose, please also take care of job dependency. Dependent jobs should ideally go to the same server.

We've not added support for job dependencies yet for multi-server

2021-01-07 20:58 UTC, arungrover commented
> > Any route you choose, please also take care of job dependency. Dependent jobs should ideally go to the same server.
> 
> 
> 
> We've not added support for job dependencies yet for multi-server 

Ok, do we know how we are going to address job dependency?

2021-01-07 20:58 UTC, agrawalravi90 commented
> Ok, do we know how we are going to address job dependency?

Not yet, it has not been designed yet

2021-01-07 22:39 UTC, nithinj commented
@agrawalravi90 ,
The first job being submitted from a qsub daemon will still be to a random one in the list. Then it tries to walk through the list till it completes it. I will mention it in the description.

2021-01-08 00:11 UTC, agrawalravi90 commented
@nithinj thanks for clarifying. I still think that it's not really any better than the simpler randomizer that we have right now since it still will not guarantee uniform distribution. Can you do some real world tests to see how much better this is? Have distinct shell sessions submit 10k jobs before and after this change and see how the jobs get distributed between multiple servers.

2021-01-08 03:25 UTC, suresh-thelkar commented
@nithinj, The changes look good to me. As @agrawalravi90 said we can actually do some multi-server tests to know whether the distribution of jobs is fair.

2021-01-08 17:56 UTC, agrawalravi90 commented
@nithinj on second thoughts, can you please do the following test instead:
- have separate qsub daemon process submit jobs after a random sleep time. This will imitate real world behavior better.
- run the test for a fixed amount of time, say 1 minute, and then measure how many jobs each server got.

2021-01-08 18:54 UTC, nithinj commented
@agrawalravi90 ,
I have updated the description with examples of submitting jobs before and after the changes.

For the sake of explanation, let's say we have 2 servers and 10 jobs. To start with we have one terminal where qsub is getting submitted. If it is purely random, in the worst case it could get distributed 10 vs 0. The best case is fair distribution 5 vs 5, which will be always guaranteed by the proposed approach.

Now you can interpolate this into N terminals. We can think optimistically that one skewed result might get offset by another terminal and so on. But it can be the other way, making the distribution even worse. OTOH, the proposed approach guarantees a fair distribution with each terminal, dividing the overall job distribution equally amongst instances.

2021-01-08 22:48 UTC, agrawalravi90 commented
@nithinj I understand how the logic will work, what I'm trying to convey is that this will not guarantee uniform distribution of jobs across the server instances, so I don't like the PR title, it seems misleading. If you think that round robin is actually better than random, even though neither will guarantee uniform distribution, then please do a realistic test to show that it will be better: have multiple qsub processes submit jobs at different frequencies for a given time period and measure what the distribution was.

If round robin performs better, then of course we should do it, I'm just asking for a proper test.

2021-01-11 16:34 UTC, nithinj commented
@agrawalravi90 ,
PR doesn't claim uniform load across instances but uniform no of jobs, both are different.
I have shown how a single qsub will result in a skewed result. We have discussed what will happen if you interpolate it. It can get worse but cannot beat the proposed approach. More testing will prove how worse it can get. But I do not see much value in doing it.

2021-01-11 18:33 UTC, agrawalravi90 commented
> PR doesn't claim uniform load across instances but uniform no of jobs, both are different.

That's what i said, this PR claims that jobs will be distributed uniformly across servers, which is incorrect.

> I have shown how a single qsub will result in a skewed result. We have discussed what will happen if you interpolate it. It can get better/worse but cannot beat the proposed approach. More testing will prove how better/worse it can get. But I do not see much value in doing so.

Since this change won't guarantee uniform distribution of jobs, the only potential gain from it is a "better" distribution of jobs than the current approach, so you need to show how it is better. Real sites don't have a single qsub process, so showing that a single qsub process performs better is not a good test. It's like if I created an alternative to TPP and only showed that my algorithm performs better for a single host, it's not a good test, just like yours isn't. If you still disagree, please feel free to get opinions from other maintainers, if they agree with you then I'll back off.

2021-02-05 04:48 UTC, subhasisb commented
We need to ascertain the pros and cons of this approach and compare with other similar approaches. There is no point in keeping this PR open for a long time. Closing it for now. Please keep the code in your repo and raise after due design considerations.

2021-02-05 04:48 UTC, closed without merging