Moving IFL Wrappers method to a new file from ptl_sevrer.py
openpbs/openpbs pull request #2195
Opened 2021-01-11 13:01 UTC by birbalsain

#### Describe Bug or Feature

Move ifl wrapper method to a new class 

#### Describe Your Change
moved ifl wrapper methods to a new file, ptl_wrappers.py

#### Link to Design Doc

#### Attach Test and Valgrind Logs/Output

Description: Tests from given sources on platforms UBUNTU1804, SUSE15, UBUNTU1604, CENTOS8, RHEL8, CENTOS7, RHEL7, SLES12, SLES15
Platforms: UBUNTU1804,SUSE15,UBUNTU1604,CENTOS8,RHEL8,CENTOS7,RHEL7,SLES12,SLES15
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|5557|2987|3|294|0|1|2662|
Description: Tests from given sources on platforms UBUNTU1804, SUSE15, UBUNTU1604, CENTOS8, RHEL8, CENTOS7, RHEL7, SLES12, SLES15, WIN2K16
Platforms: UBUNTU1804,SUSE15,UBUNTU1604,CENTOS8,RHEL8,CENTOS7,RHEL7,SLES12,SLES15,WIN2K16
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|5561|1201|6|7|0|5|1183|
Description: Rerun Only Failed Tests From #5561
Platforms: UBUNTU1804,SUSE15,UBUNTU1604,CENTOS8,RHEL8,CENTOS7,RHEL7,SLES12,SLES15,WIN2K16
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|5564|13|5|0|0|0|8|

2021-02-03 07:15 UTC, birbalsain commented
**before changes**
Description: Tests from given sources on platforms UBUNTU1804, SUSE15, UBUNTU1604, CENTOS8, RHEL8, CENTOS7, RHEL7, SLES12, SLES15, WIN2K16
Platforms: UBUNTU1804,SUSE15,UBUNTU1604,CENTOS8,RHEL8,CENTOS7,RHEL7,SLES12,SLES15,WIN2K16
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|5915|3815|4|0|0|1|3810|

no mom on server
Description: Automated nightly regression
Platforms: UBUNTU1804,SUSE15,UBUNTU1604,CENTOS8,RHEL8,CENTOS7,RHEL7,SLES12,SLES15,WIN2K16
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|5911|3815|39|11|0|1|3764|

**after changes**
Description: Tests from given sources on platforms UBUNTU1804, SUSE15, UBUNTU1604, CENTOS8, RHEL8, CENTOS7, RHEL7, SLES12, SLES15, WIN2K16
Platforms: UBUNTU1804,SUSE15,UBUNTU1604,CENTOS8,RHEL8,CENTOS7,RHEL7,SLES12,SLES15,WIN2K16
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|5919|3815|4|0|0|1|3810|

no mom on server
Description: Tests from given sources on platforms UBUNTU1804, SUSE15, UBUNTU1604, CENTOS8, RHEL8, CENTOS7, RHEL7, SLES12, SLES15, WIN2K16
Platforms: UBUNTU1804,SUSE15,UBUNTU1604,CENTOS8,RHEL8,CENTOS7,RHEL7,SLES12,SLES15,WIN2K16
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|5918|3815|49|88|0|1|3677|

Description: Rerun Only Failed Tests From #5918
Platforms: UBUNTU1804,SUSE15,UBUNTU1604,CENTOS8,RHEL8,CENTOS7,RHEL7,SLES12,SLES15,WIN2K16
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|5935|137|34|2|0|0|101|

2021-02-05 05:02 UTC, subhasisb commented
No activity from 25 days, any reason to keep this PR open?

2021-02-05 05:08 UTC, birbalsain commented
@subhasisb I done some changes in this week and it is ready for review but not getting review.

2021-02-05 07:49 UTC, kjakkali requested changes

2021-02-05 07:49 UTC, kjakkali commented on test/fw/ptl/lib/pbs_testlib.py
> +from ptl.lib.ptl_wrappers import *
we don't need wrapper import here

2021-02-05 07:49 UTC, kjakkali commented on test/fw/ptl/lib/ptl_server.py
>      def set_op_mode(self, mode):
move it wrapper class

2021-02-05 07:49 UTC, kjakkali commented on test/fw/ptl/lib/ptl_server.py
>      def set_connect_timeout(self, timeout=0):
Look for other functions also , if possible move them  new wrapper class.

2021-02-05 07:49 UTC, kjakkali commented on test/fw/ptl/lib/ptl_server.py
> -                    c = self._connect(self.hostname)
do we need remove this?

2021-02-05 07:49 UTC, kjakkali commented on test/fw/ptl/lib/ptl_server.py
> -    def counter(self, obj_type=None, attrib=None, id=None, extend=None,
Let counter() be in server class.

2021-02-05 07:49 UTC, kjakkali commented on test/fw/ptl/lib/ptl_wrappers.py
> +    actions = ExpectActions()
move it to server class.

2021-02-08 03:49 UTC, birbalsain commented
no_mom_on_server
Description: Tests from given sources on platforms UBUNTU1804, SUSE15, UBUNTU1604, CENTOS8, RHEL8, CENTOS7, RHEL7, SLES12, SLES15, WIN2K16
Platforms: UBUNTU1804,SUSE15,UBUNTU1604,CENTOS8,RHEL8,CENTOS7,RHEL7,SLES12,SLES15,WIN2K16
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|5967|3815|26|96|0|11|3682|

mom_on_server
Description: Tests from given sources on platforms UBUNTU1804, SUSE15, UBUNTU1604, CENTOS8, RHEL8, CENTOS7, RHEL7, SLES12, SLES15, WIN2K16
Platforms: UBUNTU1804,SUSE15,UBUNTU1604,CENTOS8,RHEL8,CENTOS7,RHEL7,SLES12,SLES15,WIN2K16
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|5966|3815|3|0|0|1|3811|

2021-02-12 07:09 UTC, kjakkali requested changes

2021-02-12 07:09 UTC, kjakkali commented on test/fw/ptl/lib/ptl_wrappers.py
> +            statlist = [self._filter(obj_type, newattr, id, extend, op=op,
Add log level argument . make DEBUG as default value.

2021-02-12 16:44 UTC, birbalsain commented
**After Changes
mom_on_server and no_mom_on_server**
![after_changes](https://user-images.githubusercontent.com/37452058/107795618-e7f78f80-6d7e-11eb-8072-36ec76abeb6a.PNG)


**Run separately not started tests**
 Description: Tests from given sources on platforms UBUNTU1804, SUSE15, UBUNTU1604, CENTOS8, RHEL8, CENTOS7, RHEL7, SLES12, SLES15, WIN2K16
Platforms: UBUNTU1804,SUSE15,UBUNTU1604,CENTOS8,RHEL8,CENTOS7,RHEL7,SLES12,SLES15,WIN2K16
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|6066|52|0|0|0|0|52|

2021-02-15 11:00 UTC, kjakkali approved these changes
Changes looks good to me.

2021-02-15 12:49 UTC, hirenvadalia approved these changes

2021-02-15 12:50 UTC, merged