test_rsc_used of TestMomMockRun is failing while verifying the job attributes on slow machines
openpbs/openpbs pull request #2226
Opened 2021-01-29 08:40 UTC by Klovely

#### Describe Bug or Feature
Test "test_rsc_used" of TestMomMockRun is failing while verifying the job attributes on slow machine some times in weekend regression with below error

ptl.lib.ptl_error.PtlExpectError: rc=1, rv=False, msg=expected on server xarm-05-c8p1:  no data for job_state = R && substate = 42 job 0.xarm-05-c8p1 attempt: 180

#### Describe Your Change
Test is failed because of race condition , in test we are submitting job which request walltime = 00:00:05 and confirming job is in R and state=42 
but on slow machine sometimes command itself take 5 sec to respond , so by the time job went to E state and it failed in getting expected value in qstat -f and 
test failed in PTL expect

Solution : Increased resource_list.walltime value  from 00:00:05 to 00:00:20sec

#### Attach Test and Valgrind Logs/Output

2021-01-29 18:42 UTC, bhroam requested changes

2021-01-29 18:42 UTC, bhroam commented on test/tests/functional/pbs_mom_mock_run.py
> +        time.sleep(22)
I'd shorten the message so it'd fit on one line with the logger.  You can won't need to say how long you are sleeping if you replace the sleep with self.server.expect(JOB, 'queue', op=UNSET, id=jid, expect=22)

2021-02-01 11:03 UTC, Klovely commented
latest logs
[latest_logs.txt](https://github.com/openpbs/openpbs/files/5903540/latest_logs.txt)

2021-02-01 22:01 UTC, bhroam approved these changes
LGTM

2021-02-01 22:54 UTC, Klovely commented
[latest_log.txt](https://github.com/openpbs/openpbs/files/5907301/latest_log.txt)

2021-02-02 04:52 UTC, dinesh1306 approved these changes

2021-02-02 05:50 UTC, prakashcv13 commented
merging based on reviews from Bhroam and Dinesh

2021-02-02 05:50 UTC, merged