Partial C++ refactor of resource_resv and node_info
openpbs/openpbs pull request #2245
Opened 2021-02-08 22:32 UTC by bhroam

#### Describe Bug or Feature
For part of the scheduler persistence work for multi-server, some of the scheduler objects needed to be refactored to be more C++ like.  In order to keep the size of the overall scheduler-persistence PR down, this is being done first.

#### Describe Your Change
Refactored resource_resv and node_info to be partial C++ objects.  They now have a full fledged constructor and destructor, but not copy constructor.  I didn't create a copy constructor because the objects are very cross-linked, so it would be difficult to write one.  In the spirit of agile, I did what was required now.

#### Attach Test and Valgrind Logs/Output
I'm still running a TH3 run, logs to be attached later.

2021-02-09 22:44 UTC, vstumpf requested changes
some comments

2021-02-09 22:44 UTC, vstumpf commented on src/scheduler/resource_resv.cpp
> +		nresresv = new resource_resv(name.c_str());
I'm not sure I like this, why not overload dup_resource_resv without a name argument and pass it to dup_resource_resv() with oresresv->name?

2021-02-09 22:44 UTC, vstumpf commented on src/scheduler/simulate.cpp
> +	if ((te = new timed_event) == NULL) {
add () to `new timed_event`

2021-02-09 22:44 UTC, vstumpf commented on src/scheduler/simulate.h
> +	enum timed_event_types event_type, time_t event_time, const std::string& name = {});
same here, instead of using a default empty arg, use overloading

2021-02-10 00:42 UTC, arungrover requested changes
Minor comments

2021-02-10 00:42 UTC, arungrover commented on src/scheduler/prev_job_info.cpp
> +prev_job_info::prev_job_info(prev_job_info&& opj) noexcept: name(std::move(opj.name)), entity_name(std::move(opj.name))
I think there is a typo here, entity_name should be moved to entity_name.

2021-02-10 00:42 UTC, arungrover commented on src/scheduler/resource_resv.cpp
> +dup_resource_resv(resource_resv *oresresv, server_info *nsinfo, queue_info *nqinfo, const std::string& name)
Please update the function header.

2021-02-10 00:42 UTC, arungrover commented on src/scheduler/resource_resv.cpp
>  		return NULL;
free schd_error here.

2021-02-10 23:29 UTC, bhroam commented on src/scheduler/limits.cpp
> +	log_eventf(PBSEVENT_DEBUG4, PBS_EVENTCLASS_JOB, LOG_DEBUG, rr->name,
The function name didn't serve any purpose.  It only really told the log what type of limit we were talking about, which is in the log message itself.  I decided it was better to pass resresv->name in.  This also means it'll show up in tracejob.

2021-02-11 00:15 UTC, bhroam commented
@arungrover @vstumpf I've addressed your comments.  Please take another look.

2021-02-16 17:01 UTC, arungrover approved these changes
LGTM.
Thanks for making the changes.

2021-02-16 19:06 UTC, vstumpf requested changes
some nitpicks

you can rebase with these changes if you want.

2021-02-16 19:06 UTC, vstumpf commented on src/scheduler/node_info.cpp
> +find_node_info(node_info **ninfo_arr, const std::string& nodename)
can you add the function header?

2021-02-17 17:11 UTC, vstumpf approved these changes

2021-02-17 21:45 UTC, merged