Fix race condition in TestAcctlogRescUsedWithTwoMomHooks
openpbs/openpbs pull request #2282
Opened 2021-03-04 12:04 UTC by Klovely

#### Describe Bug or Feature
'test_Rrecord'and 'test_Erecord' of 'TestAcctlogRescUsedWithTwoMomHooks' failed on slow machine  some time with below error 

ptl.lib.ptl_error.PtlExpectError: rc=1, rv=False, msg=expected on server x50-xyz:  no data for job_state = R && substate = 42 job 2.xyz attempt: 180

Reason :- Job is of only sleep 5 sec in test_Rrecord and of sleep 1sec in test_Erecord , so there is race condition  on slow machine where some time there is delay of 5 sec to respond in command , in that case job cross the sleep time by the time job test look for job in R state with substate 42 , job is already went into E state  or finished and fail in PTL expect while 

self.server.expect(JOB, {ATTR_state: 'R'}, jid1)

#### Describe Your Change
To avoid the race condition increase sleep time in job script to 15sec

#### Attach Test and Valgrind Logs/Output

Before fix 
======
[TestAcctlogRescUsedWithTwoMomHooks_before_fix_1.txt](https://github.com/openpbs/openpbs/files/6083470/TestAcctlogRescUsedWithTwoMomHooks_before_fix_1.txt)

After fix 
=====
[TestAcctlogRescUsedWithTwoMomHooks_after_fix_10.txt](https://github.com/openpbs/openpbs/files/6083471/TestAcctlogRescUsedWithTwoMomHooks_after_fix_10.txt)

2021-03-04 12:10 UTC, Klovely commented
Note :  After fixing the race condition for test_Erecord observed its failing on further step due to product issue resource_used.walltime is coming as 0  in qstat -fx output after job finishes
Logged issue for same .

But race condition issue is got fixed and test is working fine  at step where test looking for Job  is in R state .

2021-03-04 12:16 UTC, dinesh1306 approved these changes

2021-03-04 21:19 UTC, bhroam requested changes

2021-03-04 21:19 UTC, bhroam commented on test/tests/functional/pbs_two_mom_hooks_resources_used.py
> -        test += ['sleep 5\n']
Nothing in this test requires this job script.  It also doesn't wait for the job to finish, so using the default sleep of 100 is probably best.  I'd remove the script, and just leave the sleep time alone.

2021-03-04 21:19 UTC, bhroam commented on test/tests/functional/pbs_two_mom_hooks_resources_used.py
> +        test += ['sleep 15\n']
This test also doesn't care about this job script.  I'd remove the job script, but the sleep time is right.  I'd set the sleep time of the job to 15 like you are (but in j1.set_sleep_time())

2021-03-05 02:32 UTC, Klovely commented
Latest log

[TestAcctlogRescUsedWithTwoMomHooks_after_fix2.txt](https://github.com/openpbs/openpbs/files/6087787/TestAcctlogRescUsedWithTwoMomHooks_after_fix2.txt)

2021-03-05 22:52 UTC, bhroam approved these changes

2021-03-05 22:53 UTC, merged