Fixing the proper server name at connection failure for qstat  in multi-server environement
openpbs/openpbs pull request #2312
Opened 2021-03-17 15:11 UTC by bremanandjk

#### Describe Bug or Feature

In a multi-server environment, qstat throws a connection error with the wrong server name.

#### Describe Your Change

Need to print the default server name in case of connection failure. 

#### Link to Design Doc

#### Attach Test and Valgrind Logs/Output

After fix:

[root@pbs-server pbspro]# cat /etc/pbs.conf 
PBS_SERVER=pbs-server
PBS_START_SERVER=1
PBS_START_SCHED=1
PBS_START_COMM=1
PBS_START_MOM=1
PBS_EXEC=/opt/pbs
PBS_HOME=/var/spool/pbs
PBS_CORE_LIMIT=unlimited
PBS_SCP=/bin/scp
PBS_SERVER_INSTANCES=pbs-server,spark
[root@pbs-server pbspro]# 

[root@pbs-server pbspro]# qstat
Connection refused
qstat: cannot connect to server pbs-server (errno=111)
[root@pbs-server pbspro]# pbsnodes -av
Connection refused
pbsnodes: cannot connect to server pbs-server, error=111
[root@pbs-server pbspro]#

2021-03-18 15:37 UTC, agrawalravi90 requested changes
@bremanandjk  Can you please clarify which server was qstat not able to connect to in your example? (pbs-server or spark?). From your code changes it seems like we'll always say that qstat was not able to connect to the default server, even if it was actually not able to connect to one of the other multi-servers, is that true?

2021-03-23 16:48 UTC, bremanandjk commented
> @bremanandjk Can you please clarify which server was qstat not able to connect to in your example? (pbs-server or spark?). From your code changes it seems like we'll always say that qstat was not able to connect to the default server, even if it was actually not able to connect to one of the other multi-servers, is that true?

In this example, both the servers were down. 
The expected error msg should be with the default server name in the case of multi-server mode. This is the same behaviour in pbsnodes o/p also.

2021-03-23 19:59 UTC, bremanandjk commented
@agrawalravi90 Plz let me know if you have any further questions.

2021-03-23 20:54 UTC, agrawalravi90 approved these changes
I think it would be more useful if we said which multi-server couldn't be connected to instead of the default server, for both qstat and pbsnodes. But this is better than being inconsistent, so I'm ok with it.

2021-03-23 20:56 UTC, ashwathraop approved these changes
LGTM, do you have test results?

2021-03-24 04:28 UTC, bremanandjk commented
Thanks for your approval @agrawalravi90 & @ashwathraop 
regression results:
Description: Tests from given sources on platforms UBUNTU1804, SUSE15, UBUNTU1604, CENTOS8, RHEL8, CENTOS7, RHEL7, SLES12, SLES15, WIN2K16
Platforms: UBUNTU1804,SUSE15,UBUNTU1604,CENTOS8,RHEL8,CENTOS7,RHEL7,SLES12,SLES15,WIN2K16
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|6684|3999|3|0|0|5|3991|

Description: Rerun Only Failed Tests From #6684
Platforms: UBUNTU1804,SUSE15,UBUNTU1604,CENTOS8,RHEL8,CENTOS7,RHEL7,SLES12,SLES15,WIN2K16
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|6687|3|1|0|0|0|2|

That one test case failure observed in mainline without my changes also. 

Description: Tests from given sources on platforms UBUNTU1804, SUSE15, UBUNTU1604, CENTOS8, RHEL8, CENTOS7, RHEL7, SLES12, SLES15, WIN2K16
Platforms: UBUNTU1804,SUSE15,UBUNTU1604,CENTOS8,RHEL8,CENTOS7,RHEL7,SLES12,SLES15,WIN2K16
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|6688|3|1|0|0|0|2|

2021-03-24 13:54 UTC, bremanandjk commented
> LGTM, do you have test results?

I have shared regression results and test results in description page. Its ready to merge.

2021-03-24 15:05 UTC, merged