[WIP] fix entity limit tests
openpbs/openpbs pull request #2321
Opened 2021-03-20 00:08 UTC by prakashcv13

#### Describe Bug or Feature

#### Describe Your Change

#### Link to Design Doc

#### Attach Test and Valgrind Logs/Output

2021-03-20 22:02 UTC, prakashcv13 commented
PR open for review

2021-03-23 08:44 UTC, riyazhakki commented
@prakashcv13, Changes looks good to me.
As these changes affects all the tests in the suite, can you please attach the test suite result here.

2021-03-23 10:51 UTC, prakashcv13 commented
@riyazhakki - thank you for the review. PFA the logs for all tests in the testsuite.
[TestEntityLimitsLogs.zip](https://github.com/openpbs/openpbs/files/6188876/TestEntityLimitsLogs.zip)

2021-03-23 11:46 UTC, riyazhakki approved these changes
Thank you for attaching the logs.

2021-03-23 22:23 UTC, prakashcv13 commented
@openpbs/openpbs-maintainers - request you to take this forward

2021-03-25 07:34 UTC, hirenvadalia requested changes

2021-03-25 07:34 UTC, hirenvadalia commented on test/tests/functional/pbs_test_entity_limits.py
> +        subjob1 = jid.replace('[]', '[1]')
use `j.create_subjob_id(jid, 1)` to get subjob id.

2021-03-25 08:03 UTC, hirenvadalia approved these changes

2021-03-25 09:19 UTC, merged