added delay to get mail
openpbs/openpbs pull request #2331
Opened 2021-03-26 04:51 UTC by birbalsain

#### Describe Bug or Feature
In test "Test_array_job_email.test_email_non_existent_user"  recipient is not getting the mail message upon stageout failed because e-mail sent is taking time.

#### Describe Your Change
Waiting for 10 secs to get an e-mail delivered

#### Link to Design Doc

#### Attach Test and Valgrind Logs/Output
before changes
Description: Tests from given sources on platforms SUSE15, CENTOS8, CENTOS7
Platforms: SUSE15,CENTOS8,CENTOS7
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|6716|2|1|0|0|0|1|

after changes
Description: Tests from given sources on platforms SUSE15, CENTOS8, CENTOS7
Platforms: SUSE15,CENTOS8,CENTOS7
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|6722|3|0|0|0|0|3|

2021-03-26 18:11 UTC, bhroam requested changes

2021-03-26 18:11 UTC, bhroam commented on test/tests/functional/pbs_array_job_mail.py
> +                break
You wouldn't need
```
else:
    continue
break
```
if you did:
```
if emailpass:
    break
```
at the end.

2021-03-26 18:11 UTC, bhroam commented on test/tests/functional/pbs_array_job_mail.py
> +                maillog = [x.strip() for x in ret['out'][-600:]]
If you only want the last 600 lines, maybe tail is a better option (like you use below).

2021-03-26 19:47 UTC, birbalsain commented
Description: Tests from given sources on platforms SUSE15, CENTOS8, CENTOS7
Platforms: SUSE15,CENTOS8,CENTOS7
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|6756|3|0|0|0|0|3|

2021-03-26 20:08 UTC, bhroam approved these changes
LGTM

2021-03-27 02:06 UTC, kjakkali approved these changes

2021-03-29 16:58 UTC, merged