test_advance_running_resv_reconfirm test fails if start time is in past
openpbs/openpbs pull request #2339
Opened 2021-04-05 19:08 UTC by arungrover

#### Describe Bug or Feature
On some slow machines by the time test_advance_running_resv_reconfirm submits a reservation, its start time is already in the past. This causes test to fail.

#### Describe Your Change
Changed the submission function to check the start time of the reservation and if it is seen in the past, it will move it 10 seconds in future.

#### Link to Design Doc
NA

#### Attach Test and Valgrind Logs/Output
Test running

2021-04-06 21:08 UTC, bhroam requested changes

2021-04-06 21:08 UTC, bhroam commented on test/tests/functional/pbs_multi_sched.py
> +            attr['reserve_end'] = end
There is a copy of this function in the multisched test plan.  You should modify that one as well.

2021-04-06 22:49 UTC, bhroam approved these changes
LGTM

2021-04-07 17:50 UTC, agrawalravi90 approved these changes
LGTM

2021-04-07 17:50 UTC, merged