Fixed set_resource() to always set def
openpbs/openpbs pull request #2348
Opened 2021-04-09 23:39 UTC by bhroam

#### Describe Bug or Feature
The scheduler could crash after a HUP if psets were in use

#### Describe Your Change
The scheduler will create a pset for all nodes which do not have a pset resource set.  To do this, it uses a resource it fills in with the value of "".  So we don't have to continually allocate a new schd_resource structure for this, the unset_res variable is static.  The problem is when we call set_resource(), it checks if unset_res->def is set, and if it is, it'll use that.  

The resource definitions will be requeried on a HUP (or SCH_CONFIGURE) and will change.  

On the next call to create_nodepart(), we'll use unset_res with the old def.  When we call set_resource(), it'll see the def set and use it.  That pointer is pointing at a freed resource definition.

The fix is to always find the resource definition.  The resource definitions are stored in an unordered_map, so lookups are O(1).

#### Attach Test and Valgrind Logs/Output
Before:
==294681== Invalid read of size 2
==294681==    at 0x4B78A9: set_resource(schd_resource*, char const*, resource_fields) (server_info.cpp:3126)
==294681==    by 0x494473: create_node_partitions(status*, node_info**, char const* const*, unsigned int, int*) (node_partition.cpp:445)
==294681==    by 0x4963BD: create_placement_sets(status*, server_info*) (node_partition.cpp:1266)
==294681==    by 0x4B1D4C: query_server(status*, int) (server_info.cpp:460)
==294681==    by 0x45E63B: scheduling_cycle(int, sched_cmd const*) (fifo.cpp:614)
==294681==    by 0x45E551: intermediate_schedule(int, sched_cmd const*) (fifo.cpp:547)
==294681==    by 0x45E497: schedule (fifo.cpp:503)
==294681==    by 0x4CE45D: schedule_wrapper(sched_cmd*, int) (pbs_sched_utils.cpp:1244)
==294681==    by 0x4CE339: sched_main(int, char**, int (*)(int, sched_cmd const*)) (pbs_sched_utils.cpp:1190)
==294681==    by 0x45D472: main (pbs_sched.cpp:61)
==294681==  Address 0xbc48410 is 32 bytes inside a block of size 40 free'd
==294681==    at 0x4C325FC: operator delete(void*) (vg_replace_malloc.c:584)
==294681==    by 0x4A454C: update_resource_defs(int) (resource.cpp:393)
==294681==    by 0x45E4F2: schedule (fifo.cpp:513)
==294681==    by 0x4CE45D: schedule_wrapper(sched_cmd*, int) (pbs_sched_utils.cpp:1244)
==294681==    by 0x4CE339: sched_main(int, char**, int (*)(int, sched_cmd const*)) (pbs_sched_utils.cpp:1190)

After valgrind didn't report that any more.

2021-04-12 18:29 UTC, arungrover approved these changes
LGTM
I was also thinking, why do we clear resource definitions for unset_set on a HUP. It is pretty much a static definition and can never change.

2021-04-12 18:35 UTC, bhroam commented
@arungrover It isn't that the unset_res def changes, as ALL the defs change.  We dump all the definitions and reread them all.  This means all the pointers change, and the unset_res pointer is now stale.

2021-04-12 18:39 UTC, arungrover commented
> @arungrover It isn't that the unset_res def changes, as ALL the defs change. We dump all the definitions and reread them all. This means all the pointers change, and the unset_res pointer is now stale.

Oh, I understand that. I was just saying the when we dump ALL resource definitions we shouldn't dump unset_res's resource definition because it can never change.

2021-04-12 18:45 UTC, bhroam commented
@arungrover I'm not sure what you are suggesting.  We dump all the resource defs and requery the whole lot of them.  This changes all the pointers, including the one pointed at by unset_res.  Regardless, unset_res does change.  Every time through the create_node_partitions() loop, we change its name and reset it to "".  The definition needs to be updated with the name change.

2021-04-12 19:10 UTC, arungrover commented
Sorry I misunderstood, The change is fine as it is.

2021-04-12 23:13 UTC, vstumpf approved these changes
LGTM

2021-04-12 23:19 UTC, vstumpf requested changes

2021-04-12 23:19 UTC, vstumpf commented on src/scheduler/server_info.cpp
> +		return 0;
Actually, since we return 0 here, shouldn't we check the result of set_resources in create_node_partitions?

2021-04-12 23:42 UTC, vstumpf approved these changes
LGTM, thanks for the changes!

2021-04-13 00:37 UTC, arungrover approved these changes

2021-04-13 00:37 UTC, merged