fix TPP mbox full error
openpbs/openpbs pull request #2352
Opened 2021-04-12 14:00 UTC by subhasisb

#### Describe Bug or Feature

TPP does some rudimentary amount of throttling, so that no one client can flood the pipes. The pipes are managed by the mbox data structures, which have max_size and a mbox_size. The mbox_size parameter was not being computed properly (not correctly reset to zero in certain cases). The other issue was that when receiver buffer was full, we had the logic to check the buffer at periodic intervals, but that did not work due to a missing socket fd in the comparison.

#### Describe Your Change

#### Link to Design Doc

- Set mbox_size (current size of the pipe) to 0 at some places where we clear the mbox
- passing conn->sock_fd to the deferred event enquing, since the fd is checked at the time of dequeuing (the fd was being set to -1 earlier)

#### Attach Test and Valgrind Logs/Output

Manual test procedure:
- Stand up a single host pbs installation
- Set the mom to have 1000 ncpus
- Turn off scheduling and submit 600 jobs
- Turn on scheduling
- The target receiver buffer will get full due to the quick TPP actions, but due to the bug will not get cleared
- This will result in obit acks no longer reaching the mom and many jobs will remain stuck in 41 substate

2021-04-12 14:53 UTC, nithinj approved these changes
LGTM!

2021-04-12 15:00 UTC, ashwathraop approved these changes

2021-04-12 15:10 UTC, nithinj commented
@subhasisb ,
Why a physical machine is required to reproduce this issue?

2021-04-12 15:18 UTC, subhasisb commented
> @subhasisb ,
> Why a physical machine is required to reproduce this issue?

It is possible that in usual container setup, TPP will get much less chances to be fast enough to produce this issue. In this particular case (fix part 2) the application (pbs_mom) is consuming slower than the number of messages arriving to it via TPP. Anyway, it is only a speculation right now - it might be possible to reproduce it. The point, though, is whether we can make a reliable automated test that can reliably catch the problem on most platforms.

2021-04-12 17:16 UTC, agrawalravi90 commented
@subhasisb  changes look fine to me, please run a full regression before this can be merged, thanks.

2021-04-13 04:13 UTC, hirenvadalia approved these changes

2021-04-13 05:01 UTC, agrawalravi90 requested changes
Blocking until Subhasis completes testing

2021-04-14 09:59 UTC, subhasisb commented
Description: Rerun Only Failed Tests From #7032
Platforms: SUSE15,CENTOS8,CENTOS7
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|7034|4|1|1|0|0|2|

2021-04-14 10:00 UTC, subhasisb commented
The failed and error tests are also present on master

2021-04-14 16:13 UTC, subhasisb commented
closing this PR - i am updating the alternate approach, which is to remove the checks for mbox sizes, since it does not make much difference and is adding extra complexity (the previous versions of PBS did not have this check as well, so we won't miss any functionality)

2021-04-14 16:13 UTC, closed without merging