pbs_snapshot: adding ability to obfuscate existing snapshots
openpbs/openpbs pull request #2362
Opened 2021-04-16 22:54 UTC by agrawalravi90

#### Describe Bug or Feature

Often times, it’s useful to be able to obfuscate an existing snapshot. For instance: user took a snapshot of a hard to reproduce issue but forgot to run pbs_snapshot in obfuscation mode. Since the issue is hard to reproduce, it’d be much easier if user could just obfuscate the already captured snapshot. So, this will add the ability to pbs_snapshot to be able to take an existing snapshot and obfuscate it.

#### Describe Your Change

See design doc for details

#### Link to Design Doc

https://openpbs.atlassian.net/wiki/spaces/PD/pages/2732032016/pbs+snapshot+Add+the+ability+to+obfuscate+existing+snapshots

#### Attach Test and Valgrind Logs/Output

[test_obfuscate_existing.log](https://github.com/openpbs/openpbs/files/6328185/test_obfuscate_existing.log)

2021-04-22 21:31 UTC, bhroam requested changes

2021-04-22 21:31 UTC, bhroam commented on test/fw/bin/pbs_snapshot
> +    tar.close()
You used with tar.open() above, why not here?

2021-04-23 22:03 UTC, bhroam approved these changes
LGTM

2021-04-23 22:04 UTC, bhroam commented
@agrawalravi90 CI failed due to a pycodestyle error.

2021-04-24 06:55 UTC, ashwathraop approved these changes

2021-04-26 18:02 UTC, agrawalravi90 commented
@bhroam thanks, I've fixed the pycodestyle issues, please take a look
@ashwathraop thanks for the sign-off!

2021-04-26 18:06 UTC, merged