Fix: qsub does not accept paths with colons for output files
openpbs/openpbs pull request #2371
Opened 2021-04-23 09:41 UTC by raviv1995

#### Describe Bug or Feature

Linux allows the file path to contain colons(:). However, while specifying a file path for ATTR_o or ATTR_e (output and error paths) qsub rejects a path with a colon in it.

#### Describe Your Change

If a path with a colon is provided to qsub, it considers it to include a hostname compulsorily. In `prepare_path` when we parse the string to extract a hostname we break out of the loop if the character is not a valid character for hosts (alphanumeric, periods, and hyphens). So we check for a '/' there (signifying a path with a possible colon) and continue the function with no host.

#### Attach Test and Valgrind Logs/Output

In Progress

2021-04-28 11:40 UTC, npadole20 commented
@raviv1995  please attach test logs

2021-04-28 12:30 UTC, npadole20 requested changes

2021-04-28 12:30 UTC, npadole20 commented on src/lib/Libcmds/prepare_path.c
> +				else
Move this to the line above, same for else at line no. 181

2021-04-29 06:28 UTC, npadole20 approved these changes

2021-04-29 09:32 UTC, prakashcv13 approved these changes
LGTM

2021-04-29 09:32 UTC, merged