detect and initalize postgres in pbs_habitat to support centos8
openpbs/openpbs pull request #2377
Opened 2021-04-27 15:31 UTC by wshclth

#### Describe Bug or Feature

1. In CentOS 8 PBS fails to initialize PostgreSQL properly due to the missing dependency `postgresql-server`
2. Without the instillation of `postgresql-server` and the execution of `postgresql-setup --initdb --unit postgresql`,
    `/etc/init.d/pbs start` will not start gracefully siting the error.

```
Starting PBS
PBS Home directory /var/spool/pbs needs updating.
Running /opt/pbs/libexec/pbs_habitat to update it.
***
PBS Data Service user postgres does not exist
```

3. This bug is due to the way CentOS 8 `dnf` handles the post install of `postgresql` and will not initialize itself after a 
    `dnf install ...`

#### Describe Your Change

This problem is fixed by added a dependency in the INSTALL guide requiring the install of `postgresql-setup` for CentOS 8.
PostgreSQL initialization can be checked by checking the `/var/lib/pgsql` folder. If it doesn't exist then PostgresSQL has
never been initialized as such `postgresql-setup --initdb --unit postgresql` should be run which will intern generate
the `postgres` user and setup PostgreSQL to allow for  `/etc/init.d/pbs start` to start gracefully.

2021-04-27 15:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/openpbs/openpbs?pullRequest=2377) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/openpbs/openpbs?pullRequest=2377) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/openpbs/openpbs?pullRequest=2377) it.</sub>

2021-05-02 06:54 UTC, wshclth commented
PR is ready for review.

2021-05-04 05:09 UTC, vstumpf commented
Hello, and welcome to PBS!

The changes to the INSTALL file look good, but I don't know if PBS should be setting up postgres. It could be added to INSTALL to make sure that postgres is initialized. @subhasisb thoughts?

2021-05-24 06:21 UTC, subhasisb requested changes

2021-05-24 06:21 UTC, subhasisb commented on src/cmds/scripts/pbs_habitat.in
> +	if [ ! -d /var/lib/pgsql/ ]; then
The current code checks and creates a database inside the pg_db_utility functions inside libdb. Please check this: https://github.com/openpbs/openpbs/blob/b1a41e3bfd2137d5eef006fb59808e2d311434f1/src/lib/Libdb/pgsql/pbs_db_utility#L378

That might be a more appropriate location to update/enhance.

2021-11-29 05:56 UTC, subhasisb commented
This PR is very stale. Closing for now

2021-11-29 05:56 UTC, closed without merging