Removing clienthost entry from mom config on installation
openpbs/openpbs pull request #2381
Opened 2021-05-03 22:32 UTC by nithinj

#### Describe Bug or Feature
Removing $clienthost entry from mom config file on installation

#### Describe Your Change
Server hostname and local hostname are already been added by mom internally to clienthost. So keeping clienthost pointing to server name is redundant.
PBS will not keep $clienthost in mom config at installation.

#### Link to Design Doc

#### Attach Test and Valgrind Logs/Output

Description: Tests from given sources on platforms UBUNTU1804, SUSE15, UBUNTU1604, CENTOS8, RHEL8, CENTOS7, RHEL7, SLES12, SLES15, WIN2K16
Platforms: UBUNTU1804,SUSE15,UBUNTU1604,CENTOS8,RHEL8,CENTOS7,RHEL7,SLES12,SLES15,WIN2K16
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|7407|4164|1|0|0|1|4162|

2021-05-04 01:12 UTC, arungrover approved these changes
LGTM

2021-05-05 01:51 UTC, agrawalravi90 requested changes
There was a test failure in your regression, did you rerun it?

2021-05-05 14:35 UTC, nithinj commented
@agrawalravi90 ,
I have updated the rerun results. please have a look.

2021-05-05 14:43 UTC, agrawalravi90 approved these changes
Thanks for the thorough testing, changes look fine to me.

2021-05-05 14:43 UTC, merged