handling queued limits in multi-server
openpbs/openpbs pull request #2382
Opened 2021-05-05 20:36 UTC by nithinj

#### Describe Bug or Feature
Multi-server doesn't enforce queued limits globally. qsub will return an error if the random server it reaches out to has exhausted its limits.

#### Describe Your Change
If the qsub reaches a random server where the limit is reached, it should attempt to queue jobs in the alternate servers before returning an error.

#### Link to Design Doc

#### Attach Test and Valgrind Logs/Output

[test.log](https://github.com/openpbs/openpbs/files/6430106/test.log)

2021-05-05 23:52 UTC, agrawalravi90 requested changes
Since we are still trying to figure out how to handle global data, I think we should postpone this change until we have more clarity on the future direction.

2021-05-06 04:30 UTC, subhasisb requested changes
Blocking this for now to get to a design consensus before we commit this. Thanks!

2021-05-21 16:58 UTC, nithinj commented
@agrawalravi90 & @subhasisb ,
This PR is ready for review. Please have a look.

2021-05-21 19:58 UTC, agrawalravi90 requested changes
Please fix CI issues

2021-05-21 19:58 UTC, agrawalravi90 commented on src/include/libutil.h
> +#define IS_EMPTY(str) (str && str[0] != '\0')
Shouldn't this be (!str || str[0] == '\0') ? right now, IS_EMPTY(NULL) and IS_EMPTY("\0") will return false

2021-05-21 19:58 UTC, agrawalravi90 commented on src/lib/Libifl/pbsD_submit.c
> +	if (msvr && IS_EMPTY(dest)) {
Shouldn't this be !IS_EMPTY(dest) ?

2021-05-21 19:58 UTC, agrawalravi90 commented on src/lib/Libifl/pbsD_submit.c
> +				goto error;
Not sure I understand this. If 'dest' was given, we'll not try other servers? Why? 'dest' is just a queue name, which can be shared for all servers.

Also, I think we should try all servers regardless of what the error was. Is there any case where it'd be bad if we tried all servers without checking for error?

2021-05-21 19:58 UTC, agrawalravi90 commented on src/lib/Libifl/pbsD_submit.c
> +			start = 0;
Why not leave start as the random value that we got earlier?

2021-05-26 16:25 UTC, nithinj commented
@agrawalravi90 ,
Thanks for the review. I've addressed your comments. Please have a look.

2021-05-26 19:14 UTC, agrawalravi90 approved these changes
LGTM

2021-05-27 15:59 UTC, nithinj commented
Thanks @agrawalravi90 for the approval.

@subhasisb could you take a look now.

2021-06-04 04:33 UTC, ashwathraop approved these changes
LGTM

2021-06-04 06:24 UTC, merged