Automate basic scenarios related to exechost_periodic hook
openpbs/openpbs pull request #2391
Opened 2021-05-14 18:34 UTC by Mahalty

#### Describe Bug or Feature

- Automate scenarios of exechost_periodic hook

#### Describe Your Change

- Automate following scenarios

1. exechost_periodic hook that accepts the event
2. exechost_periodic hook that is interrupted by alarm call
3. exechost_periodic hook that causes unhandled exception
4. setting custom resource through exechost_periodic hook

#### Link to Design Doc

#### Attach Test and Valgrind Logs/Output

- [Exec_periodic.txt](https://github.com/openpbs/openpbs/files/6480617/Exec_periodic.txt)

2021-05-14 18:49 UTC, bayucan approved these changes
Looks good.

2021-05-14 18:50 UTC, bayucan commented
@Mahalty : you have some failing checks, though..

2021-05-14 21:29 UTC, bhroam requested changes

2021-05-14 21:29 UTC, bhroam commented on test/tests/functional/pbs_hook_exechost_periodic.py
> +        hook_script = "x"
Instead of using a syntax error to raise an exception, why not raise one yourself?  It is clearer to the reader.

2021-05-14 21:29 UTC, bhroam commented on test/tests/functional/pbs_hook_exechost_periodic.py
> +if remote_node not in vn.keys():
No need to say vn.keys().  saying 'if remote_node not vn' is the same.  It looks at the keys. (here and below)

2021-05-14 21:29 UTC, bhroam commented on test/tests/functional/pbs_hook_exechost_periodic.py
> +common_periodic_hook_script = """import pbs
Move this above the class (or even make it a class variable, but up top).  It allows the reader to see what the hook is before reading all the tests.

2021-05-17 12:26 UTC, Mahalty commented
@bhroam  I have addressed your review comments. Please review

Latest Execution-logs:
[Exec_periodic_1.txt](https://github.com/openpbs/openpbs/files/6493717/Exec_periodic_1.txt)

2021-05-17 19:26 UTC, bhroam approved these changes
LGTM

2021-05-17 23:12 UTC, merged

2021-05-17 23:12 UTC, bayucan commented
Merged #2391 into master.