moving fairshare method from sched to fairshare
openpbs/openpbs pull request #2418
Opened 2021-06-10 06:08 UTC by birbalsain

#### Describe Bug or Feature
Moving fairshare related methods to Fairshare class from Scheduler  class

#### Describe Your Change
Moved  fairshare related methods to Fairshare class from Scheduler  class

#### Link to Design Doc

#### Attach Test and Valgrind Logs/Output

Description: Rerun All Tests From #7823
Platforms: UBUNTU1804,SUSE15,UBUNTU1604,CENTOS8,RHEL8,CENTOS7,RHEL7,SLES12,SLES15,UBUNTU2004,WIN2K16
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|7831|3374|2|0|0|0|3372|

2021-06-10 09:08 UTC, shilpakodli reviewed
I see methods are still present in pbs_sched.py file. Also there is a revert_fairshare in revert_to_defaults in pbs_sched.py which should be changed to self.fairshare.revert_fairshare. Applies to other methods too.

2021-06-10 09:16 UTC, shilpakodli commented on test/fw/ptl/lib/ptl_fairshare.py
> +        self.du.run_cmd(cmd=cmd, runas=self.user)
Include self.hostname in run_cmd.

2021-06-10 13:40 UTC, birbalsain commented
closing to restart one failed checks

2021-06-10 16:12 UTC, shilpakodli approved these changes
LGTM

2021-06-10 16:41 UTC, shilpakodli requested changes
Hi @birbalsain I see there are few tests which use the methods which moved to fairshare:
test/tests/functional/pbs_backfill_around_strictordering_ext.py
test/tests/functional/pbs_fairshare_jobsortkeys_ext.py
test/tests/functional/pbs_eligible_time_ext.py

2021-06-10 17:54 UTC, birbalsain commented
> Hi @birbalsain I see there are few tests which use the methods which moved to fairshare:
> test/tests/functional/pbs_backfill_around_strictordering_ext.py
> test/tests/functional/pbs_fairshare_jobsortkeys_ext.py
> test/tests/functional/pbs_eligible_time_ext.py

yes, Extension PR is ready , will raise after getting tests results

2021-06-11 08:12 UTC, birbalsain commented
Description: Rerun All Tests From #7831
Platforms: UBUNTU1804,SUSE15,UBUNTU1604,CENTOS8,RHEL8,CENTOS7,RHEL7,SLES12,SLES15,UBUNTU2004,WIN2K16
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|7842|3374|4|0|0|0|3370|


Description: Rerun Only Failed Tests From #7842
Platforms: UBUNTU1804,SUSE15,UBUNTU1604,CENTOS8,RHEL8,CENTOS7,RHEL7,SLES12,SLES15,UBUNTU2004
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|7844|4|0|0|0|0|4|

2021-06-11 08:57 UTC, shilpakodli approved these changes

2021-06-14 09:16 UTC, prakashcv13 approved these changes

2021-06-14 09:17 UTC, merged