Fix test_run_count_subjob_in_x of Test_run_count
openpbs/openpbs pull request #2425
Opened 2021-06-18 07:33 UTC by shilpakodli

#### Describe Bug or Feature
test_run_count_subjob_in_x  was failing with Job not in 'H' state after execjob_begin hook with reject request is created.
Test is submitting an array of jobs and while second subjob is in running state, creating execjob_begin hook with reject. On few machines, hook create and import was taking little longer time that third subjob would also get finished by the time test checks for 'H' state of third subjob.

#### Describe Your Change
Increased sleep time of Array jobs such that second subjob would run for longer time and third subjob would start executing after hook has imported.

#### Attach Test and Valgrind Logs/Output
[test_run_count_subjob_in_x_before_fix.txt](https://github.com/openpbs/openpbs/files/6675381/test_run_count_subjob_in_x_before_fix.txt)

2021-06-18 10:34 UTC, dinesh1306 approved these changes

2021-06-18 17:21 UTC, bhroam requested changes

2021-06-18 17:21 UTC, bhroam commented on test/tests/functional/pbs_test_run_count.py
> +        time.sleep(15)
Make both of these sleeps offsets in the expect.  Also consider adding a logger message explaining what you are doing.

2021-06-21 13:40 UTC, dinesh1306 approved these changes

2021-06-22 06:45 UTC, shilpakodli commented
@bhroam I have addressed your review comments, Please review latest code changes.
[test_run_count_subjob_in_x_latest_logs.txt](https://github.com/openpbs/openpbs/files/6691798/test_run_count_subjob_in_x_latest_logs.txt)

2021-06-22 19:40 UTC, bhroam approved these changes
LGTM

2021-06-22 19:40 UTC, merged