Enhance PTL MoM
openpbs/openpbs pull request #2433
Opened 2021-06-28 11:02 UTC by sakshamgarg

#### Describe Bug or Feature

Enhance the current PTL MoM framework

#### Describe Your Change

Added 4 more APIs in MoM class and made changes in the test cases
1. get_formed_path
2. rm
3. isfile
4. listdir

#### Attach Test and Valgrind Logs/Output

2021-06-28 19:24 UTC, bhroam commented
Why do we need these in mom?  We have them in DshUtils.

2021-07-01 05:32 UTC, vishwaks requested changes

2021-07-01 05:32 UTC, vishwaks commented on test/fw/ptl/lib/ptl_mom.py
> +    def rm(self, hostname=None, path=None, sudo=False, runas=None,
we can remove hostname argument for this API also.

2021-07-02 06:34 UTC, vishwaks approved these changes
Looks good to me.

2021-07-02 08:19 UTC, npadole20 approved these changes

2021-07-02 18:59 UTC, bayucan commented
The changes looked fine. Is there an accompanying test logs for this on the Linux side?

2021-07-06 06:49 UTC, bayucan approved these changes
Looks good. I've seen the test results.

2021-07-06 06:50 UTC, merged