Test 'test_exechost_periodic_accept' of TestHookExechostPeriodic is failing intermittently while verifying server-logs
openpbs/openpbs pull request #2441
Opened 2021-07-02 07:42 UTC by Mahalty

#### Describe Bug or Feature

- Test 'test_exechost_periodic_accept' of TestHookExechostPeriodic is failing intermittently while verifying server-logs

#### Describe Your Change

-  In the hook script we are updating resource of a invalid vnode. Periodic hook upon encountering an invalid node ’, proceeds to create one and the test is verifying this by verifying the following msg "autocreated vnode <vnode name>". In the current test, the test is verifying the existence of this log msg and along with that it is also verifying that the msg is received from first mom. The test is failing intermittently as the log msg in failed case has been sent from the other mom. So updating the test to check jsut for the log msg instead of checking from which mom the msg has been recieved.

#### Link to Design Doc

#### Attach Test and Valgrind Logs/Output

2021-07-02 19:26 UTC, bayucan commented
Code update looks fine. Please attach test log.

2021-07-07 23:49 UTC, bhroam approved these changes

2021-07-08 07:10 UTC, Mahalty commented
@bayucan @bhroam  I have made few more changes and attached execution logs. Kindly review

2021-07-08 17:53 UTC, bayucan requested changes

2021-07-08 17:53 UTC, bayucan commented on test/tests/functional/pbs_hook_exechost_periodic.py
>          exp_msg3 = msg2 + common_msg2
I'm seeing msg1 and msg2 to be the same, so exp_msg2 and exp_msg3 are also the same.

2021-07-08 22:06 UTC, bhroam commented on test/tests/functional/pbs_hook_exechost_periodic.py
> +        node = k
If you are only searching for 1, then I'd suggest breaking.

2021-07-09 04:09 UTC, Mahalty commented
@bayucan  and @bhroam  I have addressed your review comments. Kindly review

Latest execution-logs:
[Exec_periodic_updated.txt](https://github.com/openpbs/openpbs/files/6788633/Exec_periodic_updated.txt)

2021-07-09 17:06 UTC, bayucan approved these changes
Looks good.

2021-07-09 17:18 UTC, bayucan commented
@bhroam : are you still okay with the latest commit? If so, I can merge this now.

2021-07-09 23:38 UTC, merged