Added missed attribute in Fairshare class
openpbs/openpbs pull request #2444
Opened 2021-07-02 16:25 UTC by birbalsain

#### Describe Bug or Feature
Attribute "self.logprefix " is not defined in class Fairshare. fs_re and fs_tag are not used in Scheduler class.

#### Describe Your Change
removed fs_re and fs_tag from Scheduler class and added missed attribute "self.logprefix"

#### Link to Design Doc

#### Attach Test and Valgrind Logs/Output

mom_on_server

Description: Tests from given sources on platforms UBUNTU1804, SUSE15, UBUNTU1604, CENTOS8, RHEL8, CENTOS7, RHEL7, SLES12, SLES15, WIN2K16, UBUNTU2004
Platforms: UBUNTU1804,SUSE15,UBUNTU1604,CENTOS8,RHEL8,CENTOS7,RHEL7,SLES12,SLES15,WIN2K16,UBUNTU2004
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|8066|4177|2|0|0|1|4174|

no_mom_on_server

Description: Tests from given sources on platforms UBUNTU1804, SUSE15, UBUNTU1604, CENTOS8, RHEL8, CENTOS7, RHEL7, SLES12, SLES15, WIN2K16, UBUNTU2004
Platforms: UBUNTU1804,SUSE15,UBUNTU1604,CENTOS8,RHEL8,CENTOS7,RHEL7,SLES12,SLES15,WIN2K16,UBUNTU2004
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|8065|4177|18|6|0|13|4140|

2021-07-06 04:22 UTC, dinesh1306 approved these changes

2021-07-07 04:39 UTC, hirenvadalia requested changes

2021-07-07 04:39 UTC, hirenvadalia commented on test/fw/ptl/lib/ptl_fairshare.py
> +        self.logprefix = logprefix
I think Fairshare class should have its own logprefix like `fs-${self.sc_name}-${self.user}` instead using sched one

2021-07-09 11:02 UTC, hirenvadalia approved these changes

2021-07-09 11:02 UTC, merged