Update test 'test_submit_large_env' of TestQsubPerformance accordingly
openpbs/openpbs pull request #2447
Opened 2021-07-09 03:32 UTC by Mahalty

#### Describe Bug or Feature

- Update test 'test_submit_large_env' of TestQsubPerformance accordingly

#### Describe Your Change

- In the test we are submitting 1k jobs as pbsuser --> set env through os.environ --> submit another 1k jobs as pbsuser. After this the test is calculating the time diff between the first and last job submitted job (before and after setting env)

We currently run test as pbsroot and the env which is being set while be present in pbsroot's shell but not in pbsuser's shell

Also in the test we are setting env varibale in the shell which will not affect qsub performance..We need to modify test in such a way that it should consider submitting job through -V and -v in qsub.

#### Link to Design Doc

#### Attach Test and Valgrind Logs/Output

- [Execution_logs_TestQsubPerformance.txt](https://github.com/openpbs/openpbs/files/6788515/Execution_logs_TestQsubPerformance.txt)

2021-07-09 09:14 UTC, visheshh requested changes

2021-07-09 09:14 UTC, visheshh commented on test/tests/performance/pbs_qsub_performance.py
> +        self.submit_jobs()
Measure time inside submit jobs only for the for loop and return the time.

2021-07-09 11:51 UTC, Mahalty commented
Execution-logs
[Execution_logs_TestQsubPerformance.txt](https://github.com/openpbs/openpbs/files/6791082/Execution_logs_TestQsubPerformance.txt)

2021-07-09 14:06 UTC, visheshh commented
@Mahalty , Thanks for making changes, Can you please run the tests with --repeat-count=10 and add the json report. If the job submission time is inconsistent, we might need to increase the number of jobs.

2021-07-09 14:08 UTC, visheshh requested changes

2021-07-09 14:08 UTC, visheshh commented on test/tests/performance/pbs_qsub_performance.py
>              start_time = time.time()
start and end time should be outside the loop.

2021-07-09 17:44 UTC, Mahalty commented
[Execution_logs_TestQsubPerformance.txt](https://github.com/openpbs/openpbs/files/6793085/Execution_logs_TestQsubPerformance.txt)
[ptl_test_results.json.txt](https://github.com/openpbs/openpbs/files/6793095/ptl_test_results.json.txt)

2021-07-09 18:29 UTC, Mahalty commented
[ptl_test_results1.json.txt](https://github.com/openpbs/openpbs/files/6793281/ptl_test_results1.json.txt)
[Execution_logs_TestQsubPerformance.txt](https://github.com/openpbs/openpbs/files/6793283/Execution_logs_TestQsubPerformance.txt)

2021-07-09 23:36 UTC, bhroam commented on test/tests/performance/pbs_qsub_performance.py
> +            subprocess.call(job_sub_arg, shell=True, env=env)
Can't you do this through run_cmd()?  I thought it was extended a while back to take an environment.

2021-07-12 07:42 UTC, visheshh approved these changes
LGTM. pending bhroam's comments I sign off.

2021-07-12 18:32 UTC, bhroam commented
FYI, azure pipelines failed due to pycodestyle.  You have a couple lines which are too long.

2021-07-13 10:34 UTC, Mahalty commented
[Execution_logs_TestQsubPerformance_runcmd.txt](https://github.com/openpbs/openpbs/files/6808167/Execution_logs_TestQsubPerformance_runcmd.txt)

[ptl_test_results_run_cmd.json.txt](https://github.com/openpbs/openpbs/files/6808174/ptl_test_results_run_cmd.json.txt)

2021-07-13 11:54 UTC, visheshh approved these changes
LGTM

2021-07-13 19:03 UTC, bhroam approved these changes
LGTM

2021-07-13 19:05 UTC, bhroam commented
I retriggered azure-pipelines.  I'll merge it when they pass.

2021-07-13 19:59 UTC, merged