fix few tests from TestJobArray failed due to race condition
openpbs/openpbs pull request #2456
Opened 2021-07-19 15:18 UTC by dinesh1306

#### Describe Bug or Feature
following tests are failing from TestJobArray due to race condition.

- **test_subjob_wrong_state**:-
in the test after restarting PBS Server test is checking for MoM state = free, but sometime all sub-jobs from array are in R state due to MoM state is job-busy. when one of the sub-job got completed Mom state is comes as free.
Then in test PTL is checking for no. of running jobs=200, but while checking MoM state = free few sub jobs completed and test got failed.

- **test_queue_deletion_after_terminated_subjob**:-
On cpuset machine when we restart PBS Server, running jobs on MoM get requeued and while requeue execjob_end and execjob epiogue hooks get executed. to execute it take some time and job remains in E state due to while we deleting the job it returns error 'qdel: Request invalid for state of job <job-id>'. 

#### Describe Your Change

- **test_subjob_wrong_state**:- 
Need to check MoM state is free or job-busy, if MoM state is free then only trigger scheduling cycle otherwise no need to scheduling cycle as all jobs are already scheduled.

- **test_queue_deletion_after_terminated_subjob**:- 
Need to first check second sub-job is in R state and then delete array job.

#### Link to Design Doc

#### Attach Test and Valgrind Logs/Output

Before Fix:
[res_test_queue_deletion_after_terminated_subjob_before_fix.txt](https://github.com/openpbs/openpbs/files/6842059/res_test_queue_deletion_after_terminated_subjob_before_fix.txt)
[res_test_subjob_wrong_state_before_fix.txt](https://github.com/openpbs/openpbs/files/6842062/res_test_subjob_wrong_state_before_fix.txt)

After Fix:
[res_test_subjob_wrong_state_after_change_1.txt](https://github.com/openpbs/openpbs/files/6842064/res_test_subjob_wrong_state_after_change_1.txt)
[res_test_subjob_wrong_state_after_change_2.txt](https://github.com/openpbs/openpbs/files/6842065/res_test_subjob_wrong_state_after_change_2.txt)
[res_test_subjob_wrong_state_after_change_3.txt](https://github.com/openpbs/openpbs/files/6842066/res_test_subjob_wrong_state_after_change_3.txt)
[res_test_subjob_wrong_state_after_change_4.txt](https://github.com/openpbs/openpbs/files/6842067/res_test_subjob_wrong_state_after_change_4.txt)
[res_test_subjob_wrong_state_after_change_5.txt](https://github.com/openpbs/openpbs/files/6842068/res_test_subjob_wrong_state_after_change_5.txt)

[res_test_queue_deletion_after_terminated_subjob_after_change_cpuset_1.txt](https://github.com/openpbs/openpbs/files/6842069/res_test_queue_deletion_after_terminated_subjob_after_change_cpuset_1.txt)
[res_test_queue_deletion_after_terminated_subjob_after_change_cpuset_2.txt](https://github.com/openpbs/openpbs/files/6842072/res_test_queue_deletion_after_terminated_subjob_after_change_cpuset_2.txt)
[res_test_queue_deletion_after_terminated_subjob_after_change_cpuset_3.txt](https://github.com/openpbs/openpbs/files/6842073/res_test_queue_deletion_after_terminated_subjob_after_change_cpuset_3.txt)
[res_test_queue_deletion_after_terminated_subjob_after_change_cpuset_4.txt](https://github.com/openpbs/openpbs/files/6842074/res_test_queue_deletion_after_terminated_subjob_after_change_cpuset_4.txt)
[res_test_queue_deletion_after_terminated_subjob_after_change_cpuset_5.txt](https://github.com/openpbs/openpbs/files/6842075/res_test_queue_deletion_after_terminated_subjob_after_change_cpuset_5.txt)

2021-07-19 17:31 UTC, shilpakodli approved these changes
Changes looks good to me.

2021-07-19 19:40 UTC, bhroam requested changes

2021-07-19 19:40 UTC, bhroam commented on test/tests/functional/pbs_job_array.py
> +            time.sleep(5)
What licenses are we talking about here?  If we're talking about PBS licenses, it's going to hang the server while they are being gathered.  The status() will hang.  I don't think we need to sleep.

2021-07-19 19:40 UTC, bhroam commented on test/tests/functional/pbs_job_array.py
> +            self.server.manager(MGR_CMD_SET, MGR_OBJ_SERVER,
use self.scheduler.run_scheduling_cycle().  Running a cycle is pretty harmless, If you remove the above sleep, then you can remove the status() call and just run the cycle in all cases.

2021-07-21 10:55 UTC, dinesh1306 commented
@bhroam , I have update code. Please take a look.
[res_after_comment_1.txt](https://github.com/openpbs/openpbs/files/6855010/res_after_comment_1.txt)
[res_after_comment_2.txt](https://github.com/openpbs/openpbs/files/6855012/res_after_comment_2.txt)
[res_after_comment_3.txt](https://github.com/openpbs/openpbs/files/6855013/res_after_comment_3.txt)
[res_after_comment_4.txt](https://github.com/openpbs/openpbs/files/6855014/res_after_comment_4.txt)
[res_after_comment_5.txt](https://github.com/openpbs/openpbs/files/6855016/res_after_comment_5.txt)

2021-07-21 19:58 UTC, bhroam approved these changes
My only question is if expect() works on a subjob without extend='t'.  If the test is passing, it does.  I've just never done it.

I'll sign off.

2021-07-26 09:26 UTC, merged