PTL cleanup_jobs() method should use actual mom host name
openpbs/openpbs pull request #2479
Opened 2021-08-18 02:07 UTC by birbalsain

#### Describe Bug or Feature
In PTL, cleanup_jobs() method is not taking the actual hostname of moms if moms are in large number. when moms are in large number then mom naming is mom-0, mom1,mom-2 so on , these are not the actual mom host machine name.

#### Describe Your Change
PTL cleanup_jobs()  method uses actual mom host name.

#### Link to Design Doc

#### Attach Test and Valgrind Logs/Output
mom on server
Description: Tests from given sources on platforms UBUNTU1804, UBUNTU1604, CENTOS8, RHEL8, CENTOS7, RHEL7, SLES12, SLES15, UBUNTU2004
Platforms: UBUNTU1804,UBUNTU1604,CENTOS8,RHEL8,CENTOS7,RHEL7,SLES12,SLES15,UBUNTU2004
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|8452|3275|2|0|0|0|3273|

no mom on server
Description: Tests from given sources on platforms UBUNTU1804, UBUNTU1604, CENTOS8, RHEL8, CENTOS7, RHEL7, SLES12, SLES15, UBUNTU2004
Platforms: UBUNTU1804,UBUNTU1604,CENTOS8,RHEL8,CENTOS7,RHEL7,SLES12,SLES15,UBUNTU2004
Profile: regression
|ID|TOTAL|FAIL|ERROR|TIMEDOUT|SKIP|PASS|
|--|--|--|--|--|--|--|
|8451|3275|12|8|0|12|3243|

2021-08-18 05:34 UTC, visheshh approved these changes
LGTM

2021-08-18 05:40 UTC, visheshh requested changes
@birbalsain You can use pbsnodes -v host -F json and use key value pairs to fetch mom name and avoid for loop.

2021-08-18 09:28 UTC, visheshh requested changes

2021-08-18 09:28 UTC, visheshh commented on test/fw/ptl/lib/ptl_server.py
> +                host = ((ret['out'][6]).split(':'))[1].split('"')[1]
join the ret['out'] and use the keys

2021-08-18 09:29 UTC, visheshh commented on test/fw/ptl/lib/ptl_server.py
> +                host = ((ret['out'][6]).split(':'))[1].split('"')[1]
pbsnodes_json = json.loads('\n'.ret['out']))

2021-08-18 12:10 UTC, visheshh approved these changes
I sign off. Thanks for making changes

2021-09-03 05:57 UTC, kjakkali commented
@openpbs/openpbs-maintainers  Please take this forward.

2021-09-03 22:55 UTC, bayucan approved these changes
Looks fine.

2021-09-03 22:55 UTC, merged