Remove Python object reference cycles from base and server classes
openpbs/openpbs pull request #2501
Opened 2021-11-17 21:55 UTC by toonen

#### Describe Bug or Feature

In the PBS Python server classes (ex: `_job`) used during hook invocation, some class level attributes, such as the `_attributes_hook_set` and those set to a `PbsAttributeDescriptor`, exist as dictionaries whose keys are a references to objects instantiated from those classes.  This creates a reference cycle where an object refers to the class (in `__class__`) and the class level dictionaries hold one or more references to the object.  The following diagram is an example of such a cycle.

```
_job._attributes_hook_set[_job()] = {'id': None}
^    ^                    ^         ^
|    |                    |         Value cached
|    |                    Object Instance of class _job, increments reference to that object.
|    |                    This also stores the object reference on the class which persists until python is restarted.
|    Class attribute 
Class
```

These cycles prevent the Python garbage collector from being able to free the event object and all objects it directly or indirectly references until such time as the class attributes are deleted.  Over time this results in a large accumulation of objects that are no longer needed.  The current solution is to periodically restart the Python interpreter.  When the interpreter is shutdown, the class attributes are deleted, breaking the reference cycles and allowing the objects to be deleted as well.  Unfortunately, periodically restarting the interpreter has side effects, including crashing the server when some Python extension modules (shared libraries) are used.

#### Describe Your Change

To prevent these reference cycles and allow the objects to be freed by the garbage collector, we replaced the existing dictionaries with instances of a `WeakKeyDictionary` provided by the weakref module.  The object references in the dictionaries will persist until such time as the last strong reference to the object is removed.  At that time, the object will be freed and any references to it in the dictionaries will automatically be removed.

With these changes, we are able to disable the Python interpreter restart and observe that the amount of memory used by the server,  as well as the number of objects being tracked by the Python garbage collector, remains relatively constant over time.

2021-11-18 20:07 UTC, bayucan reviewed
This is a nice discovery! Thanks. It looks reasonable. I would like evidence of testing, and in particular, please run the following PTL tests, which are under tests/functional. These tests make use of Python hooks:
[test.list2.txt](https://github.com/openpbs/openpbs/files/7565670/test.list2.txt)

2022-01-03 17:24 UTC, bayucan commented
@toonen : anything else to add to this PR (i.e. test output) or is it good to go? I've seen the test results and they looked fine.

2022-01-03 17:27 UTC, toonen commented
@bayucan I believe it is ready to be merged.  @ericpershey included the test results in a previous comment.

2022-01-03 17:29 UTC, bayucan approved these changes
Looks good.

2022-01-03 17:30 UTC, bayucan commented
@toonen : ok, I approved this. Will wait for another reviewer before merging. @openpbs/openpbs-maintainers : this needs another erviewer.

2022-01-08 01:03 UTC, bhroam requested changes

2022-01-08 01:03 UTC, bhroam commented on test/tests/functional/pbs_acct_log.py
> +        jid1 = self.server.submit(j, extend='x')
Same here, I don't think extend=x does anything on a submit.

2022-01-10 16:38 UTC, ericpershey commented on test/tests/functional/pbs_acct_log.py
> +                            BatchUtils().convert_duration("00:00:42")})
I was doing deeper tests with types.  Will change it to 42.

2022-01-10 18:34 UTC, ericpershey commented
@bhroam Thanks for all of the feedback.  Commit 28167703df239f1bd8944df6609480c956e2ab58 addresses the various issues you raised.

2022-01-10 20:15 UTC, bhroam approved these changes
LGTM

2022-01-10 20:16 UTC, bhroam commented
@bayucan do you want to take another look, or should this be merged?

2022-01-10 21:00 UTC, bayucan commented
@bhroam : still looks good to me. I'll merge.

2022-01-10 21:00 UTC, merged

2022-01-10 21:00 UTC, bayucan commented
Merged #2501 into master.