Fixed Compilation Warnings
openpbs/openpbs pull request #2577
Opened 2023-03-26 06:21 UTC by higopika

#### Describe Bug or Feature
There are two types of warnings in compilation 
In Ubuntu 20 and 22
1. daemon_protect.c:98:3: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result] 
seen only in Ubuntu 22
3. qsub.c:2169:33: note: destination object of size 0 allocated by ‘malloc’

#### Describe Your Change
fixed all warnings by checking the error and logging in case of error. No functional changes has been introduced.

#### Link to Design Doc
Not Applicable

#### Attach Test and Valgrind Logs/Output
attaching logs before and after fix.

Before Fix
[warnings_Ubuntu_20.txt](https://github.com/openpbs/openpbs/files/11070909/warnings_Ubuntu_20.txt)
[warnings_Ubuntu_22.txt](https://github.com/openpbs/openpbs/files/11070911/warnings_Ubuntu_22.txt)

After Fix
[warnings_after_fix.txt](https://github.com/openpbs/openpbs/files/11070914/warnings_after_fix.txt)

2023-03-26 06:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/openpbs/openpbs?pullRequest=2577) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/openpbs/openpbs?pullRequest=2577) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/openpbs/openpbs?pullRequest=2577) it.</sub>

2023-03-28 04:40 UTC, higopika commented
I got this error in the CI build. So added braces to fix them. I have updated the description with this one as well.

../../../src/mom_rcp/rcp.c: In function ‘source’:
../../../src/mom_rcp/rcp.c:777:7: error: suggest explicit braces to avoid ambiguous ‘else’ [-Werror=dangling-else]
    if (haderr)
       ^
../../../src/mom_rcp/rcp.c:820:6: error: suggest explicit braces to avoid ambiguous ‘else’ [-Werror=dangling-else]
   if (!haderr)
      ^
cc1: all warnings being treated as errors

2023-03-29 16:04 UTC, higopika commented on src/mom_rcp/rcp.c
> +				errx(-1, __func__, "write failed. ERR : %s",strerror(errno));
I have assumed the change is the space and I have made the change. I hope I am right.

2023-04-07 11:48 UTC, riyazhakki commented on src/lib/Libtpp/tpp_em.c
> +			return -1;
```suggestion
	                tpp_unlock(&mbox->mbox_mutex);
			return -1;
```

There may be a deadlock if this is not done

2023-04-10 16:44 UTC, higopika commented on azure-pipelines.yml
> +  vmImage: 'ubuntu-20.04'
runcheck failed saying ubuntu 18.04 is deprecated. So I had to change to 20.04.

2023-04-10 16:53 UTC, higopika commented on azure-pipelines.yml
> +  vmImage: 'ubuntu-20.04'
I updated the description with all the changes done for this pull request.

2023-04-12 18:02 UTC, prakashcv13 requested changes
for all the new "if"s added - the braces are not needed - if removing the braces are not causing any warnings - can we remove those.

for *.py changes - could you please update the summary as to why we are converting some strings to regular expressions

2023-05-09 21:09 UTC, prakashcv13 approved these changes

2023-05-09 21:09 UTC, merged