Handle corrupt standing reservations
openpbs/openpbs pull request #2632
Opened 2024-03-14 10:45 UTC by kiliakis

#### Describe Bug or Feature
Handles identified issues with standing reservations that are corrupted and then crash the server (and scheduler).
The Root cause is unknown (probable race condition including a reservation that is degraded and reconfirmed at an "awkward" moment).

#### Describe Your Change

These changes will:

- consistently use the reserve_execvnodes DB attribute (and corresponding internal attributes in server and scheduler) with N entries to mean these are for the last N occurrences.
- will do bounds checking when accessing elements in the unrolled array created from it (to handle a number of entries that is unexpectedly short -- reconfirmation can change the number of entries).
- will avoid exiting routines with a standing reservation in an inconsistent state, especially when partially changed but not written to the DB.
- will degrade a reservation that is either missing resv_vnodes or reserve_execvnodes or has a reserve_execvnodes that is too short for the current reserve_index and occurrence count.
- will modify the scheduler to not give up on such reservations when asked to reconfirm them, accepting the current reserve_vnode as detailed above (treating occurrences that have no entry as 'currently nodeless', with the scheduler free to assign any nodes it can find to them).
- when restarting the server, will create the timed tasks to move reservations in RESV_DELETING_JOBS to finished state (and beyond); the current code assumes the timed task will 'take care of things' but when we restart the server that task will be gone.
- The logging was also improved to make it more easy to see exactly what the server or scheduler did not like about a reservation, and in the case of a standing reservation, which occurrence it was having trouble with.

#### Link to Design Doc

#### Attach Test and Valgrind Logs/Output

It's impossible to create a PTL test for these without the root cause, but I have successfully tested the changes against the following kind of standing reservation:
- reservation with the current index set to a finished reservation, start/end/duration consistent with the next occurrence, and a reserve_execvnode that is missing some entries wrt the reserve_index value

**A session that demonstrates the issue before fixing it:** 

```bash

All daemons in one node: ub22-single

08:26:12 root ub22-single  ~ 
→ ps -ef | grep pbs
root        2537       1  0 08:20 ?        00:00:00 /opt/pbs/sbin/pbs_comm
root        2547       1  0 08:20 ?        00:00:00 /opt/pbs/sbin/pbs_mom
root        2559       1  0 08:20 ?        00:00:00 /opt/pbs/sbin/pbs_sched
root        2605       1  0 08:20 ?        00:00:00 /opt/pbs/sbin/pbs_ds_monitor monitor
postgres    2627       1  0 08:20 ?        00:00:00 /usr/lib/postgresql/14/bin/postgres -D /var/spool/pbs/datastore -p 15007
postgres    2667    2627  0 08:20 ?        00:00:00 postgres: postgres pbs_datastore 172.18.1.10(38260) idle
root        2668       1  0 08:20 ?        00:00:00 /opt/pbs/sbin/pbs_server.bin
root        2920     152  0 08:35 pts/1    00:00:00 grep --color=auto pbs

Submit a standing reservation

08:37:31 pbsuser ub22-single  ~ 
→ pbs_rsub -lselect=1:ncpus=4 -R 0839 -D 2:00 -r "FREQ=HOURLY;COUNT=4"
S1.ub22-single UNCONFIRMED

The reservation is confirmed:

08:37:49 pbsuser ub22-single  ~ 
→ pbs_rstat
Resv ID    Queue    User     State             Start / Duration / End              
---------------------------------------------------------------------
S1.ub22-si S1       pbsuser@ CO  

08:38:43 pbsuser ub22-single  ~ 
→ sleep 60; pbs_rstat; sleep 120; pbs_rstat
Resv ID    Queue    User     State             Start / Duration / End              
---------------------------------------------------------------------
S1.ub22-si S1       pbsuser@ RN          Today 08:39 / 120 / Today 08:41      
Resv ID    Queue    User     State             Start / Duration / End              
---------------------------------------------------------------------
S1.ub22-si S1       pbsuser@ CO          Today 09:39 / 120 / Today 09:41

Stop PBS: 

08:35:24 root ub22-single  ~ 
→ /etc/init.d/pbs stop
Stopping PBS
Shutting server down with qterm.
PBS server - was pid: 2668
PBS mom - was pid: 2547
PBS sched - was pid: 2559
PBS comm - was pid: 2537
Waiting for shutdown to complete

Start the dataservice
09:00:18 root ub22-single  ~ 
→ /opt/pbs/sbin/pbs_dataservice start
Starting PBS Data Service..

09:01:15 root ub22-single  ~ 
→ ps -ef | grep pbs
root        2924     243  0 08:35 pts/2    00:00:00 su pbsuser
pbsuser     2926       1  0 08:35 ?        00:00:00 /lib/systemd/systemd --user
pbsuser     2927    2926  0 08:35 ?        00:00:00 (sd-pam)
pbsuser     2932    2924  0 08:35 pts/2    00:00:00 bash
root        3530       1  0 09:01 ?        00:00:00 /opt/pbs/sbin/pbs_ds_monitor monitor
postgres    3552       1  0 09:01 ?        00:00:00 /usr/lib/postgresql/14/bin/postgres -D /var/spool/pbs/datastore -p 15007
root        3577     152  0 09:01 pts/1    00:00:00 grep --color=auto pbs

Corrupt the reservation entry in the datastore.

state and substate set to RESV_FINISHED, 
reserve_index set to 1 but times corresponding to the second occurrence,
number of elements in reserve_execvnodes inconsistent (too short) with reserve_index.

09:16:25 root ub22-single  ~ 
→ cat corrupt_db_1.sql 
set search_path to pbs,public;
select * from resv;
update resv set ri_state = 6;
update resv set ri_substate = 6;
update resv set attributes = attributes || '"reserve_state"=>"11.6"';
update resv set attributes = attributes || '"reserve_substate"=>"11.6"';
update resv set attributes = attributes || '"reserve_index"=>"11.1"';
update resv set attributes = attributes || '"reserve_execvnodes"=>"11.2#(ub22-single:ncpus=4){0-1}"';
select * from resv;

09:22:19 root ub22-single  ~ 
→ /usr/lib/postgresql/14/bin/psql -A -t -p 15007 -U postgres -d pbs_datastore -f corrupt_db_1.sql
SET
S1.ub22-single|S1|6|6|1710322740|1710322860|120|1710319140|4097|2024-03-13 08:41:05.505724|2024-03-13 08:37:49.567258|"ctime"=>"11.1710319069", "euser"=>"11.pbsuser", "mtime"=>"11.1710319265", "queue"=>"11.S1", "egroup"=>"15.tstgrp00", "server"=>"11.ub22-single", "hop_count"=>"11.1", "partition"=>"11.pbs-default", "resv_nodes"=>"11.(ub22-single:ncpus=4)", "reserve_end"=>"11.1710322860", "schedselect"=>"15.1:ncpus=4", "Reserve_Name"=>"11.NULL", "Reserve_Owner"=>"11.pbsuser@ub22-single", "Variable_List"=>"11.PBS_O_LOGNAME=pbsuser,PBS_O_HOST=ub22-single,PBS_O_MAIL=/var/mail/pbsuser,PBS_TZID=UTC", "reserve_count"=>"11.4", "reserve_index"=>"11.2", "reserve_rrule"=>"11.FREQ=HOURLY;COUNT=4", "reserve_start"=>"11.1710322740", "reserve_state"=>"11.2", "Authorized_Users"=>"11.pbsuser@ub22-single", "reserve_duration"=>"11.120", "reserve_standing"=>"11.1", "reserve_substate"=>"11.2", "reserve_timezone"=>"11.UTC", "reserve_execvnodes"=>"11.4#(ub22-single:ncpus=4){0-3}", "Resource_List.ncpus"=>"15.4", "Resource_List.place"=>"11.free", "Resource_List.nodect"=>"15.1", "Resource_List.select"=>"9.1:ncpus=4", "Resource_List.walltime"=>"11.00:02:00"
UPDATE 1
UPDATE 1
UPDATE 1
UPDATE 1
UPDATE 1
UPDATE 1
S1.ub22-single|S1|6|6|1710322740|1710322860|120|1710319140|4097|2024-03-13 08:41:05.505724|2024-03-13 08:37:49.567258|"ctime"=>"11.1710319069", "euser"=>"11.pbsuser", "mtime"=>"11.1710319265", "queue"=>"11.S1", "egroup"=>"15.tstgrp00", "server"=>"11.ub22-single", "hop_count"=>"11.1", "partition"=>"11.pbs-default", "resv_nodes"=>"11.(ub22-single:ncpus=4)", "reserve_end"=>"11.1710322860", "schedselect"=>"15.1:ncpus=4", "Reserve_Name"=>"11.NULL", "Reserve_Owner"=>"11.pbsuser@ub22-single", "Variable_List"=>"11.PBS_O_LOGNAME=pbsuser,PBS_O_HOST=ub22-single,PBS_O_MAIL=/var/mail/pbsuser,PBS_TZID=UTC", "reserve_count"=>"11.4", "reserve_index"=>"11.1", "reserve_rrule"=>"11.FREQ=HOURLY;COUNT=4", "reserve_start"=>"11.1710322740", "reserve_state"=>"11.6", "Authorized_Users"=>"11.pbsuser@ub22-single", "reserve_duration"=>"11.120", "reserve_standing"=>"11.1", "reserve_substate"=>"11.6", "r [...]

2024-03-15 08:48 UTC, kiliakis commented
I'm also attaching the ptl test logs. The test suites I ran are the following (i.e. all related to reservations):

- TestPbsResvAlter 
- StandingResvQuasihang 
- TestMaintenanceReservations
- TestReservations
- TestReservationRequests

There are a few tests that occasionally fail or pass both before and after the suggested fix. 
- pbs_reservations.py:test_degraded_advance_reservations
- pbs_reservations.py:test_degraded_advance_running_reservations
- pbs_reservations.py:test_degraded_standing_reservations
- pbs_reservations.py:test_degraded_standing_running_reservations


[ptl_after_fix_all.txt](https://github.com/openpbs/openpbs/files/14613048/ptl_after_fix_all.txt)
[ptl_before_fix_all.txt](https://github.com/openpbs/openpbs/files/14613051/ptl_before_fix_all.txt)

2024-03-20 08:34 UTC, kiliakis commented on src/scheduler/resv_info.cpp
> +					resresv->resv->resv_state = RESV_DEGRADED;
@bhroam thanks for the review! Do you suggest not setting the state to degraded at all here?

2024-03-20 08:36 UTC, kiliakis commented on src/scheduler/resv_info.cpp
> +			/* string_dup returns NULL when input is NULL pointer */
Comment removed

2024-03-20 08:36 UTC, kiliakis commented on src/scheduler/resv_info.cpp
> +			*/
Comment removed.

2024-03-20 08:37 UTC, kiliakis commented on src/scheduler/resv_info.cpp
> +						           __func__, j + 1);
Converted to debug level 3 (PBSEVENT_DEBUG3)

2024-03-20 08:37 UTC, kiliakis commented on src/scheduler/resv_info.cpp
> +						           "%s: occurence %d has no execvnodes, using empty vector",
Converted to debug level 3 (PBSEVENT_DEBUG3)

2024-03-20 08:39 UTC, kiliakis commented on src/server/node_manager.c
> +	char *execvnodes = NULL;
moved both `execvnodes `and `occurrence` to the scope they are used.

2024-03-20 08:39 UTC, kiliakis commented on src/server/svr_jobfunc.c
> +                    is_degraded = 1;
Corrected formatting with clang-format.

2024-03-20 16:27 UTC, bhroam requested changes

2024-03-20 16:27 UTC, bhroam commented on src/scheduler/resv_info.cpp
> +							   __func__, j + 1);
This is an error, so I was fine with it at the log level.  I just want the message to be more clear.  An admin won't understand what using an empty vector means.  Either just drop that part or explain what it means.

2024-03-27 16:00 UTC, bhroam approved these changes

2024-04-04 11:16 UTC, merged