fix TPP leaf can get stuck after fork()
openpbs/openpbs pull request #2651
Opened 2024-07-01 07:31 UTC by vchlum

#### Describe Bug or Feature

If the TPP leaf uses functions that use locks, it can get stuck in the child after a fork. It concerns the functions like `gethostbyaddr()` or `krb5_init_context()` and possibly others...

E.g.: First thread calls `gethostbyaddr()`, which locks its lock. Another thread can fork before `gethostbyaddr()` unlocks the lock, thus keeping the lock locked in the child. Later the child process can get stuck waiting to unlock the lock.

Here is an older stack trace of the `gethostbyaddr()` stuck while moving a job to another server:
```
#1 0x00007fc62820e479 in _L_lock_909 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2 0x00007fc62820e2a0 in __GI___pthread_mutex_lock (mutex=0x7fc62290a320 <lock>) at ../nptl/pthread_mutex_lock.c:79
#3 0x00007fc622702cc7 in _nss_files_gethostbyaddr_r (addr=0x7ffca2512680, len=4, af=2,
result=0x7fc6269891e0 <resbuf>, buffer=0x875a10 "", buflen=1024, errnop=0x7fc6294716b0, herrnop=0x7ffca25115f4)
at nss_files/files-hosts.c:110
#4 0x00007fc6266d9373 in __gethostbyaddr_r (addr=addr@entry=0x7ffca2512680, len=len@entry=4, type=type@entry=2,
resbuf=resbuf@entry=0x7fc6269891e0 <resbuf>, buffer=0x875a10 "", buflen=1024,
result=result@entry=0x7ffca25115f8, h_errnop=h_errnop@entry=0x7ffca25115f4) at ../nss/getXXbyYY_r.c:266
#5 0x00007fc6266d90f5 in gethostbyaddr (addr=0x7ffca2512680, len=4, type=2) at ../nss/getXXbyYY.c:116
#6 0x00000000004b5e03 in send_job (jobp=0x150f6cb0, hostaddr=1317066841, port=15001, move_type=1,
post_func=0x4b50b9 <post_movejob>, preq=0x41f87070) at /tmp/pbspro-src/src/server/svr_movejob.c:988
#7 0x00000000004b690e in net_move (jobp=0x150f6cb0, req=0x41f87070) at /tmp/pbspro-src/src/server/svr_movejob.c:1302
#8 0x00000000004b4bc3 in svr_movejob (jobp=0x150f6cb0, destination=0x41f8751a "global@pbs.elixir-czech.cz:15001",
req=0x41f87070) at /tmp/pbspro-src/src/server/svr_movejob.c:203
#9 0x000000000048173c in req_movejob (req=0x41f87070) at /tmp/pbspro-src/src/server/req_movejob.c:157
#10 0x0000000000468948 in dispatch_request (sfds=27, request=0x41f87070)
at /tmp/pbspro-src/src/server/process_request.c:795
#11 0x00000000004684ae in process_request (sfds=27) at /tmp/pbspro-src/src/server/process_request.c:537
#12 0x00000000004e1a07 in process_socket (sock=27) at /tmp/pbspro-src/src/lib/Libnet/net_server.c:504
#13 0x00000000004e1d16 in wait_request (waittime=2, priority_context=0x2af9fc80)
at /tmp/pbspro-src/src/lib/Libnet/net_server.c:620
#14 0x000000000046685c in main (argc=1, argv=0x7ffca2517748) at /tmp/pbspro-src/src/server/pbsd_main.c:2137
```

And here is a stack trace of stuck krb5_init_context():
```
#0 __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1 0x00002b34f062bbb5 in __GI___pthread_mutex_lock (mutex=0x2b34f18f6fa0) at ../nptl/pthread_mutex_lock.c:80
#2 0x00002b34f169b2d8 in ?? () from /usr/lib/x86_64-linux-gnu/libkrb5.so.26
#3 0x00002b34f1693c3f in krb5_init_context () from /usr/lib/x86_64-linux-gnu/libkrb5.so.26
#4 0x00005613356aa739 in get_job_info_from_job (pjob=0x5613369c46e0, ptask=0x0, job_info=0x561336736b88)
at /tmp/pbspro-src/src/resmom/renew_creds.c:716
#5 0x00005613356a9483 in init_ticket_from_job (pjob=0x5613369c46e0, ptask=0x0, ticket=0x561336736b80, cred_action=1)
at /tmp/pbspro-src/src/resmom/renew_creds.c:192
#6 0x00005613356aab3d in cred_by_job (pjob=0x5613369c46e0, cred_action=1) at /tmp/pbspro-src/src/resmom/renew_creds.c:856
#7 0x00005613356a4594 in start_process (ptask=0x56133666d1a0, argv=0x5613366dba80, envp=0x5613366fa050, nodemux=false)
at /tmp/pbspro-src/src/resmom/start_exec.c:4884
#8 0x00005613356681c0 in im_request (stream=1, version=5) at /tmp/pbspro-src/src/resmom/mom_comm.c:3966
#9 0x0000561335682801 in do_rpp (stream=1) at /tmp/pbspro-src/src/resmom/mom_main.c:7055
#10 0x000056133568287c in rpp_request (fd=10) at /tmp/pbspro-src/src/resmom/mom_main.c:7099
#11 0x00005613356b8287 in process_socket (sock=10) at /tmp/pbspro-src/src/lib/Libnet/net_server.c:512
#12 0x00005613356b85af in wait_request (waittime=2, priority_context=0x0) at /tmp/pbspro-src/src/lib/Libnet/net_server.c:628
#13 0x0000561335682d65 in finish_loop (waittime=2) at /tmp/pbspro-src/src/resmom/mom_main.c:7390
#14 0x0000561335689cce in main (argc=2, argv=0x7ffe86541d28) at /tmp/pbspro-src/src/resmom/mom_main.c:10637
```

Although the stack traces are from older versions of this software, the bug is still there and this problem occasionally happens.

#### Describe Your Change

I suggest adding a new lock `tpp_fork_lock` that is kept locked in `tpp_transport.c:work()` except for `tpp_em_wait()` part. In the case of `fork()`, the fork prepare function will demand the lock `tpp_fork_lock` and thus wait to finish the previous work started in another thread. 

#### Link to Design Doc

#### Attach Test and Valgrind Logs/Output

This bug is hard to replicate. A PTL test can not be created and even simulation in gdb is not feasible. I think the smoke test is enough to show nothing is broken after the fix in this case. A long DNS response while moving a job can increase the chance of occurring but is not guaranteed.

2024-07-03 04:35 UTC, subhasisb commented
Hi @vchlum I don't think we need to add another lock. In fact, I don't like this change that locks the work thread that way. 
Besides for the gethostbyaddr + thread+ forking issue we already have code that should address that. Please see tpp_transport.c:507. There is a tpp_nslookup_mutex that is acquired in tpp_nslookup_atfork_prepare() handler so that both  the parent and child processes after the fork has the lock in a "known" state and can simply unlock it. If another nss routine had acquired this lock that the "prepare" handler would have to wait. This is anyway the classic way to solve this issue with threading + forking.

2024-07-03 04:36 UTC, subhasisb requested changes
Hi @vchlum I don't think we need to add another lock. In fact, I don't like this change that locks the work thread that way.
Besides for the gethostbyaddr + thread+ forking issue we already have code that should address that. Please see tpp_transport.c:507. There is a tpp_nslookup_mutex that is acquired in tpp_nslookup_atfork_prepare() handler so that both the parent and child processes after the fork has the lock in a "known" state and can simply unlock it. If another nss routine had acquired this lock that the "prepare" handler would have to wait. This is anyway the classic way to solve this issue with threading + forking.

You can do something similar for the kerberos functions as well...

2024-07-08 16:21 UTC, vchlum commented
Hi @subhasisb! Thank you for your comment. You are right. The `gethostbyaddr` has been addressed.

I extended the current GSS lock to address the forking issue in gss/krb. Please see the new patch. I also renamed this PR to meet this purpose better.

The original patch was intended as a robust solution without further checks on the implementations of particular functions with hardly any impact on performance. 

Manual test of job submission with gss/krb to show nothing is broken after this patch here:
```
torque1.grid.cesnet.cz$ PBS_AUTH_METHOD=GSS PBS_ENCRYPT_METHOD=GSS pbsnodes -a
torque1
     Mom = torque1.grid.cesnet.cz
     Port = 15002
     pbs_version = 23.06.06
     ntype = PBS
     state = free
     pcpus = 2
     resources_available.arch = linux
     resources_available.host = torque1
     resources_available.hpmem = 0b
     resources_available.mem = 1965mb
     resources_available.ncpus = 2
     resources_available.ngpus = 0
     resources_available.vmem = 2918mb
     resources_available.vnode = torque1
     resources_assigned.accelerator_memory = 0kb
     resources_assigned.cgswap = 0kb
     resources_assigned.hbmem = 0kb
     resources_assigned.mem = 0kb
     resources_assigned.naccelerators = 0
     resources_assigned.ncpus = 0
     resources_assigned.vmem = 0kb
     resv_enable = True
     sharing = default_shared
     license = l
     last_state_change_time = Mon Jul  8 17:12:17 2024
     last_used_time = Mon Jul  8 17:34:52 2024

torque1.grid.cesnet.cz$ PBS_AUTH_METHOD=GSS PBS_ENCRYPT_METHOD=GSS qsub -I
qsub: waiting for job 12299.torque1.grid.cesnet.cz to start
qsub: job 12299.torque1.grid.cesnet.cz ready

torque1.grid.cesnet.cz$ klist
Credentials cache: FILE:/tmp/krb5cc_pbsjob_12299.torque1.grid.cesnet.cz
        Principal: vchlum@META

  Issued                Expires               Principal
Jul  8 17:12:29 2024  Jul  9 17:12:29 2024  krbtgt/META@META
Jul  8 18:04:15 2024  Jul  9 17:12:29 2024  afs/ics.muni.cz@META
Jul  8 18:04:15 2024  Jul  9 17:12:29 2024  krbtgt/ZCU.CZ@META
Jul  8 18:04:15 2024  Jul  9 10:04:15 2024  afs/zcu.cz@ZCU.CZ
torque1.grid.cesnet.cz$ PBS_AUTH_METHOD=GSS PBS_ENCRYPT_METHOD=GSS qstat
Job id            Name             User              Time Use S Queue
----------------  ---------------- ----------------  -------- - -----
12299.torque1     STDIN            vchlum            00:00:00 R default         
torque1.grid.cesnet.cz$
```

2024-07-09 05:49 UTC, subhasisb requested changes
generally looks good. I think you can also remove the tpp_nslookup_mutex and the associated atfork handlers (tpp_nslookup_atfork_prepare() etc) since this solution should cover for that as well?

With your solution once we are inside the transport thread, no other thread can fork unless we are in the event poll (the place safe to allow forks).

2024-07-09 05:49 UTC, subhasisb commented on src/lib/Libtpp/tpp_client.c
> +	if (pthread_atfork(tpp_atfork_prepare, tpp_atfork_parent, tpp_terminate)) {
I feel we should register the atfork handlers before we call tpp_transport_init() (ie, before tpp starts the threads), ie, before line 646, could be even much much earlier as well - dont see any harm

2024-07-09 06:30 UTC, vchlum commented
Sorry @subhasisb, I am a bit confused now. I thought you didn't like the original solution where no other thread can fork unless we are in the event poll...

So I changed to a finer solution for just the krb functions.

With the original solution, we really can remove tpp_nslookup_mutex. Should I revert to the first solution? Could you clarify, please?

2024-07-09 07:44 UTC, subhasisb commented
hey @vchlum my mistake. I forgot the older conversation and did not read that and reviewed the older code once more. I like your latest commit. I will approve it right away

2024-07-09 07:45 UTC, subhasisb approved these changes

2024-07-09 07:46 UTC, subhasisb commented
Approved. If you are also fine with the testing, I can go ahead and merge. Please confirm.

2024-07-09 08:13 UTC, vchlum commented
Testing looks good. I confirm. You can merge. Thank you.

2024-07-09 09:55 UTC, merged