qdel 123 123.svr.name -> server core dump
openpbs/openpbs pull request #2659
Opened 2024-08-10 16:02 UTC by vchlum

#### Describe Bug or Feature

qdel the same jobid with and without server name in a one line causes server crash.

> qdel 123 123.svr.name 

#### Describe Your Change

We already had a similar bug #2552, so I was inspired by its solution. The function `dedup_jobids()` can not recognize <short_jobid> and <long_jobid> as the same job.  I suggest adding the default server name to short job ids.

#### Link to Design Doc

#### Attach Test and Valgrind Logs/Output

I run full pbs_qdel.py with just s small modification to test this case: [ptl_qdel.txt](https://github.com/user-attachments/files/16570152/ptl_qdel.txt)

2024-08-11 14:23 UTC, vchlum commented
I have added one more fix on the server side... The related `pbs_idx_insert` ignored a failure code, which resulted in the segfault on the server side.  If it happens now,  the internal error (15011) is logged and segfault will not occur but none of the jobs in the qdel list are deleted. If the request is correct without duplicities, it should not happen.

New ptl: [ptl_qdel.txt](https://github.com/user-attachments/files/16573997/ptl_qdel.txt)

2024-08-21 22:38 UTC, bhroam commented
Let me see if I can find you a reviewer who better knows this code than I do.

2024-08-28 08:08 UTC, vchlum commented
I have found one more error in the related code and am working on fixing it. This particular segfault can be invoked by `qdel -W force 123 124[0] 124[1]`:

```
torque1.grid.cesnet.cz$ qsub -- /usr/bin/sleep 1000
71000.torque1.grid.cesnet.cz
torque1.grid.cesnet.cz$ qsub -J 0-1 -- /usr/bin/sleep 1000
71001[].torque1.grid.cesnet.cz
torque1.grid.cesnet.cz$ qdel -W force 71000.torque1.grid.cesnet.cz 71001[0].torque1.grid.cesnet.cz 71001[1].torque1.grid.cesnet.cz
```

results in:
```
Thread 1 "pbs_server.bin" received signal SIGSEGV, Segmentation fault.
reply_send (request=0x55555590b1c0) at reply_send.c:314
314			if (((request->rq_parentbr->rq_reply.brp_choice == BATCH_REPLY_CHOICE_NULL) || (request->rq_parentbr->rq_reply.brp_choice == BATCH_REPLY_CHOICE_Delete)) && (request->rq_parentbr->rq_reply.brp_code == 0)) {
(gdb) bt
#0  reply_send (request=0x55555590b1c0) at reply_send.c:314
#1  0x00005555555be910 in req_reject (code=15001, aux=0, preq=0x55555590b1c0) at reply_send.c:536
#2  0x00005555555f43b8 in chk_job_request (jobid=0x7fffffffb6a0 "\016", preq=0x55555590b1c0, rc=0x7fffffffb69c, 
    err=0x7fffffffb688) at svr_chk_owner.c:392
#3  0x00005555555bfc8f in req_deletejob (preq=0x55555590b1c0) at req_delete.c:620
#4  0x00005555555bb090 in dispatch_request (sfds=20, request=0x55555590b1c0) at process_request.c:923
#5  0x00005555555bad5f in process_request (sfds=20) at process_request.c:762
#6  0x00005555556334d9 in process_socket (sock=20) at net_server.c:510
#7  0x000055555563382b in wait_request (waittime=2, priority_context=0x555555743cd0) at net_server.c:623
#8  0x00005555555b9073 in main (argc=2, argv=0x7fffffffe9f8) at pbsd_main.c:1404
```

The reason seems to be `IS_ARRAY_Range` is not added to to job list in `init_deljoblist()`.

I am still investigating. Please postpone the review process until the next commit.

2024-09-04 15:29 UTC, nithinj approved these changes
Thanks for adding the test cases. Looks good to me!

2024-09-12 22:09 UTC, bhroam requested changes
Sorry about the delay, I was hoping a second reviewer who knew more about this fix would pick it up.  I'm not going to give much of a review about correctness.  Hopefully Nithin's review covers that.

2024-09-17 11:31 UTC, vchlum commented on src/lib/Libutil/dedup_jobids.c
> +			malloc_track[i] = 1;
Yes, it is correct. That is how `malloc_track` is used.

2024-09-17 11:34 UTC, vchlum commented on test/tests/functional/pbs_qdel.py
> +            msg = f'qdel: Unknown Job Id {unknown_jid}'
Done. Thx. 
[test_qdel_with_list_of_jobids.txt](https://github.com/user-attachments/files/17027518/test_qdel_with_list_of_jobids.txt)

2024-09-17 11:34 UTC, vchlum commented on test/tests/functional/pbs_qdel.py
> +    @requirements(num_moms=1)
No, removed.

2024-09-17 11:36 UTC, vchlum commented
Thank you @bhroam. I addressed your comments.

2024-09-17 22:02 UTC, bhroam approved these changes

2024-09-17 22:02 UTC, merged